from pathlib import Path

from sampletones_core.famitracker.builder import project_to_module
from sampletones_core.famitracker.export import write_ftm
from sampletones_core.famitracker.ftm import module_to_ftm_bytes
from sampletones_core.famitracker.specification.blocks import (
    BLOCK_COMMENTS,
    BLOCK_DPCM_SAMPLES,
    BLOCK_FRAMES,
    BLOCK_HEADER,
    BLOCK_INFO,
    BLOCK_INSTRUMENTS,
    BLOCK_PARAMS,
    BLOCK_PATTERNS,
    BLOCK_SEQUENCES,
)
from sampletones_core.famitracker.specification.channels import ChannelId
from sampletones_core.famitracker.specification.file import FTM_END_MARKER, FTM_VERSION
from sampletones_core.famitracker.specification.parameters import (
    DEFAULT_SPEED_SPLIT_POINT,
    EXPANSION_NONE,
    Machine,
)
from sampletones_core.famitracker.specification.patterns import (
    EMPTY_INSTRUMENT,
    EMPTY_VOLUME,
    NoteValue,
)
from sampletones_core.famitracker.specification.sequences import SequenceKind

from .conftest import ProjectFixture
from .reader import ParsedModule, ParsedSequence, parse_ftm

ALL_BLOCKS = [
    BLOCK_PARAMS,
    BLOCK_INFO,
    BLOCK_HEADER,
    BLOCK_INSTRUMENTS,
    BLOCK_SEQUENCES,
    BLOCK_FRAMES,
    BLOCK_PATTERNS,
    BLOCK_DPCM_SAMPLES,
    BLOCK_COMMENTS,
]


def _module_bytes(fixture: ProjectFixture) -> bytes:
    return module_to_ftm_bytes(project_to_module(fixture.project))


def _parsed(fixture: ProjectFixture) -> ParsedModule:
    return parse_ftm(_module_bytes(fixture))


def _pooled(parsed: ParsedModule, sequence_type: SequenceKind, index: int) -> ParsedSequence:
    return next(
        sequence
        for sequence in parsed.sequences
        if sequence.sequence_type == int(sequence_type) and sequence.index == index
    )


class TestFileFraming:
    def test_ends_with_end_marker(self, project_fixture: ProjectFixture) -> None:
        assert _module_bytes(project_fixture).endswith(FTM_END_MARKER)

    def test_version_matches(self, project_fixture: ProjectFixture) -> None:
        assert _parsed(project_fixture).version == FTM_VERSION

    def test_every_block_present_with_expected_version(self, project_fixture: ProjectFixture) -> None:
        versions = _parsed(project_fixture).block_versions
        for block in ALL_BLOCKS:
            assert versions[block.name] == block.version


class TestParamsBlock:
    def test_expansion_and_channels(self, project_fixture: ProjectFixture) -> None:
        params = _parsed(project_fixture).params
        assert params.expansion_chip == EXPANSION_NONE
        assert params.channel_count == 5

    def test_machine_and_engine_speed(self, project_fixture: ProjectFixture) -> None:
        params = _parsed(project_fixture).params
        assert params.machine == int(Machine.NTSC)
        assert params.engine_speed == project_fixture.project.settings.nes_frequency

    def test_speed_split_point(self, project_fixture: ProjectFixture) -> None:
        assert _parsed(project_fixture).params.speed_split_point == DEFAULT_SPEED_SPLIT_POINT


class TestInfoAndComments:
    def test_info_fields(self, project_fixture: ProjectFixture) -> None:
        info = _parsed(project_fixture).info
        assert info.title == "Demo"
        assert info.author == "Tester"
        assert info.copyright == "generated by SampleToNES"

    def test_comment_round_trips(self, project_fixture: ProjectFixture) -> None:
        assert _parsed(project_fixture).comment == "a comment"


class TestHeaderBlock:
    def test_single_track(self, project_fixture: ProjectFixture) -> None:
        assert _parsed(project_fixture).header.track_count == 1

    def test_channel_ids_in_order(self, project_fixture: ProjectFixture) -> None:
        channels = _parsed(project_fixture).header.channels
        assert [channel.channel_id for channel in channels] == [int(channel_id) for channel_id in ChannelId]

    def test_one_effect_column_per_channel(self, project_fixture: ProjectFixture) -> None:
        channels = _parsed(project_fixture).header.channels
        assert all(channel.effect_columns == 1 for channel in channels)


class TestInstrumentsBlock:
    def test_instrument_count(self, project_fixture: ProjectFixture) -> None:
        assert len(_parsed(project_fixture).instruments) == 5

    def test_all_instruments_are_2a03(self, project_fixture: ProjectFixture) -> None:
        assert all(instrument.instrument_type == 1 for instrument in _parsed(project_fixture).instruments)

    def test_instrument_names_include_generator(self, project_fixture: ProjectFixture) -> None:
        names = [instrument.name for instrument in _parsed(project_fixture).instruments]
        assert names[0] == "lead Pulse 1"
        assert "Triangle" in names[4]

    def test_volume_reference_resolves_to_populated_sequence(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        enabled, index = parsed.instruments[0].sequence_refs[int(SequenceKind.VOLUME)]
        assert enabled == 1
        assert _pooled(parsed, SequenceKind.VOLUME, index).items


class TestSequencesBlock:
    def test_looping_instrument_sequence_loops_from_start(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        pad = next(instrument for instrument in parsed.instruments if instrument.name.startswith("pad"))
        _, index = pad.sequence_refs[int(SequenceKind.VOLUME)]
        assert _pooled(parsed, SequenceKind.VOLUME, index).loop_point == 0


class TestFramesBlock:
    def test_frame_and_channel_dimensions(self, project_fixture: ProjectFixture) -> None:
        frames = _parsed(project_fixture).frames
        assert frames.frame_count == 2
        assert all(len(entry) == 5 for entry in frames.order)

    def test_timing_matches_settings(self, project_fixture: ProjectFixture) -> None:
        frames = _parsed(project_fixture).frames
        settings = project_fixture.project.settings
        assert frames.speed == settings.speed
        assert frames.tempo == settings.tempo
        assert frames.pattern_length == project_fixture.project.song.rows_per_pattern

    def test_referenced_patterns_and_empty_dpcm(self, project_fixture: ProjectFixture) -> None:
        frames = _parsed(project_fixture).frames
        assert frames.order[0][ChannelId.SQUARE1] == 0
        assert frames.order[0][ChannelId.NOISE] == 0
        assert all(entry[ChannelId.DPCM] == 0 for entry in frames.order)


class TestPatternsBlock:
    def _pattern(self, parsed: ParsedModule, channel: ChannelId, index: int):
        return next(p for p in parsed.patterns if p.channel == int(channel) and p.index == index)

    def test_only_used_channels_have_patterns(self, project_fixture: ProjectFixture) -> None:
        channels = {pattern.channel for pattern in _parsed(project_fixture).patterns}
        assert channels == {int(ChannelId.SQUARE1), int(ChannelId.NOISE)}

    def test_instrument_row(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        pattern = self._pattern(parsed, ChannelId.SQUARE1, 0)
        row = next(row for row in pattern.rows if row.row_number == 0)
        assert (row.note, row.octave) == (1, 3)
        assert row.instrument == 0
        assert row.volume == 10

    def test_note_off_row(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        pattern = self._pattern(parsed, ChannelId.SQUARE1, 0)
        row = next(row for row in pattern.rows if row.row_number == 2)
        assert row.note == int(NoteValue.HALT)
        assert row.instrument == EMPTY_INSTRUMENT

    def test_volume_only_row(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        pattern = self._pattern(parsed, ChannelId.SQUARE1, 0)
        row = next(row for row in pattern.rows if row.row_number == 4)
        assert row.note == int(NoteValue.NONE)
        assert row.instrument == EMPTY_INSTRUMENT
        assert row.volume == 5

    def test_noise_row_period_note(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        pattern = self._pattern(parsed, ChannelId.NOISE, 0)
        row = next(row for row in pattern.rows if row.row_number == 0)
        assert (row.note, row.octave) == (5, 0)


class TestDpcmBlock:
    def test_dpcm_sample_bank_is_empty(self, project_fixture: ProjectFixture) -> None:
        assert _parsed(project_fixture).dpcm_sample_count == 0


class TestWriteFtm:
    def test_writes_a_parseable_file(self, project_fixture: ProjectFixture, tmp_path: Path) -> None:
        path = tmp_path / "module.ftm"
        write_ftm(path, project_fixture.project)
        parsed = parse_ftm(path.read_bytes())
        assert parsed.version == FTM_VERSION
        assert len(parsed.instruments) == 5

    def test_empty_volume_marker_when_no_volume(self, project_fixture: ProjectFixture) -> None:
        parsed = _parsed(project_fixture)
        pattern = next(p for p in parsed.patterns if p.channel == int(ChannelId.SQUARE1) and p.index == 0)
        note_off_row = next(row for row in pattern.rows if row.row_number == 2)
        assert note_off_row.volume == EMPTY_VOLUME
