from .general import SUF_BUTTON

TAG_THEME_GRAPH_INDICATOR = "theme_graph_indicator"
TAG_THEME_GRAPH_ZERO_LINE = "theme_zero_line"
TAG_THEME_GRAPH_OVERLAY = "theme_graph_overlay"

SUF_GRAPH_PLOT = "_plot"
SUF_GRAPH_X_AXIS = "_x_axis"
SUF_GRAPH_Y_AXIS = "_y_axis"
SUF_GRAPH_LEGEND = "_legend"
SUF_GRAPH_CONTROLS = "_controls"
SUF_GRAPH_INFO = "_info"
SUF_GRAPH_RAW_DATA = "_raw_data"
SUF_GRAPH_RAW_DATA_GROUP = "_raw_data_group"
SUF_GRAPH_THEME = "_theme"
SUF_WAVEFORM_POSITION_INDICATOR = "_position_indicator"
SUF_WAVEFORM_OVERLAY = "_overlay"
SUF_BAR_PLOT_ZERO_LINE = "_zero_line"
SUF_BAR_PLOT_HOVER_BAR = "_hover_bar"
SUF_BAR_PLOT_MOUSE_HANDLER = "_mouse_handler"
SUF_BUTTON_WAVEFORM_RESET_X = f"{SUF_BUTTON}_reset_x"
SUF_BUTTON_WAVEFORM_RESET_Y = f"{SUF_BUTTON}_reset_y"
SUF_BUTTON_WAVEFORM_RESET_ALL = f"{SUF_BUTTON}_reset_all"

LBL_GRAPH_WAVEFORM_ORIGINAL = "Original"
LBL_GRAPH_WAVEFORM_RECONSTRUCTION = "Reconstruction"
LBL_BUTTON_WAVEFORM_RESET_X = "Reset X"
LBL_BUTTON_WAVEFORM_RESET_Y = "Reset Y"
LBL_BUTTON_WAVEFORM_RESET_ALL = "Reset all"
LBL_PLOT_LABEL_WAVEFORM = "Waveform display"
LBL_PLOT_AXIS_WAVEFORM_TIME = "Time (samples)"
LBL_PLOT_AXIS_WAVEFORM_AMPLITUDE = "Amplitude"
LBL_PLOT_NAME_WAVEFORM_SAMPLE = "Sample"
LBL_PLOT_LABEL_SPECTRUM = "Spectrum display"
LBL_PLOT_AXIS_SPECTRUM_X = ""
LBL_PLOT_AXIS_SPECTRUM_FREQUENCY = "Frequency"
LBL_PLOT_NAME_SPECTRUM = "Spectrum"
LBL_PLOT_LABEL_BAR = "Bar plot display"

DIM_GRAPH_WIDTH = -1
DIM_GRAPH_HEIGHT = 292
DIM_WAVEFORM_WIDTH = DIM_GRAPH_WIDTH
DIM_WAVEFORM_HEIGHT = DIM_GRAPH_HEIGHT
DIM_SPECTRUM_WIDTH = DIM_GRAPH_WIDTH
DIM_SPECTRUM_HEIGHT = DIM_GRAPH_HEIGHT
DIM_BAR_PLOT_WIDTH = DIM_GRAPH_WIDTH
DIM_BAR_PLOT_HEIGHT = 220

VAL_MIN_GRAPH_DEFAULT_X = 0.0
VAL_MAX_GRAPH_DEFAULT_X = 1.0
VAL_WAVEFORM_SAMPLE_THICKNESS = 1.5
VAL_WAVEFORM_RECONSTRUCTION_THICKNESS = 1.2
VAL_WAVEFORM_POSITION_INDICATOR_THICKNESS = 2.0
VAL_WAVEFORM_ZOOM_FACTOR = 1.1
VAL_MAX_WAVEFORM_DISPLAY_POINTS = 4096
VAL_MAX_SPECTRUM_DISPLAY_BINS = 128
VAL_MIN_GRAPH_DEFAULT_Y = -1.0
VAL_MAX_GRAPH_DEFAULT_Y = 1.0
VAL_OFFSET_SPECTRUM_LOG = 1e-2
VAL_MAX_SPECTRUM_GRAYSCALE = 255
VAL_BAR_PLOT_MIN_X = 0.0
VAL_BAR_PLOT_MIN_Y = 0.0
VAL_BAR_PLOT_MAX_Y = 100.0
VAL_BAR_PLOT_AXIS_SLOT = 1
VAL_BAR_PLOT_BAR_WEIGHT = 0.8
VAL_BAR_PLOT_ZERO_LINE_THICKNESS = 1.0
VAL_BAR_PLOT_HOVER_ALPHA = 80

COL_BAR_PLOT = (100, 200, 255, 255)
COL_BAR_PLOT_ZERO_LINE = (200, 200, 200, 255)
COL_WAVEFORM_DEFAULT = (255, 255, 255, 255)
COL_WAVEFORM_LAYER_SAMPLE = (100, 200, 255, 255)
COL_WAVEFORM_LAYER_RECONSTRUCTION = (255, 200, 100, 255)
COL_WAVEFORM_POSITION_INDICATOR = (255, 255, 255, 255)
COL_WAVEFORM_OVERLAY = (255, 255, 255, 32)
