from .general import COL_TEXT_DEFAULT

TAG_PANEL_INSTRUCTIONS_LIBRARY = "panel_instructions_library"
TAG_TEXT_INSTRUCTIONS_LIBRARY_STATUS = "text_instructions_library_status"
TAG_GROUP_INSTRUCTIONS_LIBRARY_CONTROLS = "group_instructions_library_controls"
TAG_BUTTON_INSTRUCTIONS_LIBRARY_GENERATE_LIBRARY = "button_instructions_library_generate_library"
TAG_BUTTON_INSTRUCTIONS_LIBRARY_REFRESH_LIBRARIES = "button_instructions_library_refresh_libraries"
TAG_PROGRESS_INSTRUCTIONS_LIBRARY = "progress_instructions_library"
TAG_TREE_INSTRUCTIONS_LIBRARY = "tree_instructions_library"
TAG_GROUP_INSTRUCTIONS_LIBRARY_TREE = "group_instructions_library_tree"
TAG_WINDOW_INSTRUCTIONS_LIBRARY_TREE = "window_instructions_library_tree"
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE = "window_instructions_library_instructions_choice"
TAG_DIALOG_INSTRUCTIONS_LIBRARY_LIBRARY_NOT_LOADED = "dialog_instructions_library_library_not_loaded"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION = "panel_instructions_instruction"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_PLAYER = "panel_instructions_instruction_player"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_WAVEFORM = "panel_instructions_instruction_waveform"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_SPECTRUM = "panel_instructions_instruction_spectrum"
TAG_TEXT_INSTRUCTIONS_DETAILS_INFO = "text_instructions_details_info"
TAG_PANEL_INSTRUCTIONS_DETAILS = "panel_instructions_details"
TAG_INSTRUCTION_DETAILS_GENERAL_TABLE = "instruction_details_general_table"
TAG_INSTRUCTION_DETAILS_PARAMETERS_TABLE = "instruction_details_parameters_table"
TAG_INSTRUCTION_DETAILS_GENERAL_HEADER = "instruction_details_general_header"
TAG_INSTRUCTION_DETAILS_PARAMETERS_HEADER = "instruction_details_parameters_header"
TAG_THEME_INSTRUCTIONS_LIBRARY_LIBRARY = "theme_instructions_library_library"
TAG_THEME_INSTRUCTIONS_LIBRARY_GENERATOR = "theme_instructions_library_generator"
TAG_THEME_INSTRUCTIONS_LIBRARY_GROUP = "theme_instructions_library_group"
TAG_THEME_INSTRUCTIONS_LIBRARY_INSTRUCTION = "theme_instructions_library_instruction"
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_PULSE_PITCH = (
    "window_instructions_library_instructions_choice_pulse_pitch"
)
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_PULSE_VOLUME = (
    "window_instructions_library_instructions_choice_pulse_volume"
)
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_PULSE_DUTY_CYCLE = (
    "window_instructions_library_instructions_choice_pulse_duty_cycle"
)
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_TRIANGLE_PITCH = (
    "window_instructions_library_instructions_choice_triangle_pitch"
)
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_NOISE_VOLUME = (
    "window_instructions_library_instructions_choice_noise_volume"
)
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_NOISE_PERIOD = (
    "window_instructions_library_instructions_choice_noise_period"
)
TAG_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_NOISE_SHORT = (
    "window_instructions_library_instructions_choice_noise_short"
)

SUF_GRAPH_INSTRUCTIONS_INSTRUCTION_WAVEFORM_WINDOW = "_waveform_window"
SUF_GRAPH_INSTRUCTIONS_INSTRUCTIONS_SPECTRUM_WINDOW = "_spectrum_window"
SUF_INSTRUCTION_DETAILS_TABLE = "_table"

LBL_BUTTON_INSTRUCTIONS_LIBRARY_GENERATE_LIBRARY = "Generate library"
LBL_BUTTON_INSTRUCTIONS_LIBRARY_REGENERATE_LIBRARY = "Regenerate instructions"
LBL_BUTTON_INSTRUCTIONS_LIBRARY_REFRESH_LIBRARIES = "Refresh instructions data"
LBL_INSTRUCTIONS_LIBRARY_LIBRARIES = "Instructions data"
LBL_INSTRUCTIONS_LIBRARY_AVAILABLE_LIBRARIES = "Instructions data"
LBL_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE = "Instruction choice"
LBL_NODE_INSTRUCTIONS_LIBRARY_LOAD_LIBRARY = "Click to load the library"
LBL_NODE_INSTRUCTIONS_LIBRARY_LIBRARIES = "Libraries"
LBL_INSTRUCTIONS_INSTRUCTION_WAVEFORM = "Instruction waveform"
LBL_INSTRUCTIONS_INSTRUCTION_SPECTRUM = "Instruction spectrum"
LBL_TEXT_INSTRUCTIONS_DETAILS_INSTRUCTION_DETAILS = "Instruction details"
LBL_TEXT_INSTRUCTIONS_DETAILS_PARAMETERS = "Parameters"
LBL_TEXT_INSTRUCTIONS_DETAILS_GENERAL = "General"
LBL_CELL_INSTRUCTIONS_DETAILS_GENERATOR = "Generator"
LBL_CELL_INSTRUCTIONS_DETAILS_NAME = "Instruction"
LBL_CELL_INSTRUCTIONS_DETAILS_FREQUENCY = "Frequency"
LBL_CELL_INSTRUCTIONS_DETAILS_DUTY_CYCLE = "{:.1f}% ({})"
LBL_CELL_INSTRUCTIONS_DETAILS_NO_FREQUENCY = "N/A"
LBL_CELL_INSTRUCTIONS_DETAILS_SAMPLE_LENGTH = "Sample length"
LBL_CELL_INSTRUCTIONS_DETAILS_SAMPLES = " samples"
LBL_CONTEXT_ITEM_INSTRUCTIONS_LIBRARY_LOAD_INSTRUCTION = "Load instruction"
LBL_CONTEXT_ITEM_INSTRUCTIONS_LIBRARY_LOAD_LIBRARY = "Load library"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_PULSE_PITCH = "Pitch"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_PULSE_VOLUME = "Volume"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_PULSE_DUTY_CYCLE = "Duty cycle"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_NOISE_PERIOD = "Period"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_NOISE_VOLUME = "Volume"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_NOISE_SHORT = "Short"
LBL_WINDOW_INSTRUCTIONS_LIBRARY_INSTRUCTIONS_CHOICE_TRIANGLE_PITCH = "Pitch"

MSG_LIBRARY_DISPLAY_ERROR = "Error while displaying data."
MSG_INSTRUCTIONS_LIBRARY_GENERATING = "Generating library..."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_SAVING = "Saving generated library..."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_SUCCESS = "Library generated successfully."
MSG_INSTRUCTIONS_LIBRARY_LOADING = "Library is loading..."
MSG_INSTRUCTIONS_LIBRARY_WINDOW_NOT_AVAILABLE = "Window not available."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_CANCELLATION = "Library generation cancelled."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_FAILED = "Error generating library."
MSG_INSTRUCTIONS_LIBRARY_FILE_NOT_FOUND = "The library file could not be found."
MSG_INSTRUCTIONS_LIBRARY_FILE_LOAD_ERROR = "Error while loading the library file."
MSG_INSTRUCTIONS_LIBRARY_LOAD_ERROR = "Error while loading library data."
MSG_INSTRUCTIONS_LIBRARY_INVALID_DATA_ERROR = "Invalid library data file."
MSG_INSTRUCTIONS_LIBRARY_INVALID_DATA_VALUES_ERROR = "Library data contains invalid values."
MSG_INSTRUCTIONS_DETAILS_NO_SELECTION = "No instruction selected."

TTL_DIALOG_LIBRARY_NOT_LOADED = "Library not loaded"
TTL_DIALOG_LIBRARY_GENERATION_STATUS = "Library generation status"

TPL_INSTRUCTIONS_LIBRARY_GENERATION_PROGRESS = "Generating: {}/{} "
TPL_INSTRUCTIONS_LIBRARY_NOT_LOADED = "Library {} is not loaded. Please load or generate a library."
TPL_INSTRUCTIONS_LIBRARY_NOT_EXISTS = "Library {} doesn't exist."
TPL_INSTRUCTIONS_LIBRARY_LIBRARY_EXISTS = "Library {} exists."
TPL_INSTRUCTIONS_LIBRARY_LIBRARY_LOADED = "Library {} loaded."
TPL_INSTRUCTIONS_LIBRARY_INCOMPATIBLE_VERSION_ERROR = "Incompatible library data version: {}, expected {}."
TPL_CELL_INSTRUCTIONS_DETAILS_FREQUENCY = "{:.2f} Hz"
TPL_CELL_INSTRUCTIONS_DETAILS_PITCH = "{} ({})"
TPL_CELL_INSTRUCTIONS_DETAILS_PERIOD = "p{} ({})"

DIM_PANEL_HEIGHT_INSTRUCTIONS_LIBRARY_INSTRUCTION_CHOICE = 150
DIM_INPUT_WIDTH_INSTRUCTIONS_LIBRARY_INSTRUCTION_CHOICE = 220

VAL_PRECISION_INSTRUCTIONS_DETAILS_FLOAT = 4

COL_TEXT_INSTRUCTIONS_LIBRARY_LIBRARY = COL_TEXT_DEFAULT
COL_TEXT_INSTRUCTIONS_LIBRARY_GENERATOR = (210, 232, 210, 255)
COL_TEXT_INSTRUCTIONS_LIBRARY_GROUP = (210, 232, 232, 255)
COL_TEXT_INSTRUCTIONS_LIBRARY_INSTRUCTION = (210, 210, 210, 255)
