SUF_PLAYER_PLAY = "_play"
SUF_PLAYER_PAUSE = "_pause"
SUF_PLAYER_STOP = "_stop"
SUF_PLAYER_POSITION = "_position"
SUF_PLAYER_CONTROLS_GROUP = "_controls_group"
SUF_PLAYER_NO_AUDIO_POPUP = "_no_audio_popup"
SUF_PLAYER_ERROR_POPUP = "_error_popup"

LBL_BUTTON_PLAYER_PLAY = "Play"
LBL_BUTTON_PLAYER_PAUSE = "Pause"
LBL_BUTTON_PLAYER_RESUME = "Resume"
LBL_BUTTON_PLAYER_STOP = "Stop"
LBL_TEXT_PLAYER_POSITION = "Position: "
LBL_TEXT_PLAYER_SAMPLES = " samples"

MSG_PLAYER_NO_AUDIO_LOADED = "No audio loaded."
MSG_PLAYER_AUDIO_PLAYBACK_ERROR = "Audio playback error."

TTL_DIALOG_PLAYER_NO_AUDIO = "No audio"

DIM_PANEL_WIDTH_PLAYER = -1
DIM_PANEL_HEIGHT_PLAYER = 76
DIM_TABLE_HEIGHT_PLAYER_CONTROLS = 32
