TAG_RECONSTRUCTION_NOT_LOADED_DIALOG = "reconstruction_not_loaded_dialog"
TAG_PANEL_RECONSTRUCTIONS_BROWSER = "panel_reconstructions_browser"
TAG_TREE_RECONSTRUCTIONS_BROWSER = "tree_reconstructions_browser"
TAG_GROUP_RECONSTRUCTIONS_BROWSER_TREE = "group_reconstructions_browser_tree"
TAG_WINDOW_RECONSTRUCTIONS_BROWSER_TREE = "window_reconstructions_browser_tree"
TAG_GROUP_RECONSTRUCTIONS_BROWSER_CONTROLS = "group_reconstructions_browser_controls"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_REFRESH_RECONSTRUCTIONS = "button_reconstructions_browser_refresh_reconstructions"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_FILE = "button_reconstructions_browser_reconstruct_file"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_DIRECTORY = "button_reconstructions_browser_reconstruct_directory"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION = "panel_reconstructions_reconstruction"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION_PLAYER = "panel_reconstructions_reconstruction_player"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION_WAVEFORM = "panel_reconstructions_reconstruction_waveform"
TAG_GROUP_RECONSTRUCTIONS_RECONSTRUCTION_GENERATORS = "group_reconstructions_reconstruction_generators"
TAG_GROUP_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "group_reconstructions_reconstruction_audio_source"
TAG_BUTTON_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV = "button_reconstructions_reconstruction_export_wav"
TAG_PANEL_RECONSTRUCTIONS_DETAILS = "panel_reconstructions_details"
TAG_TAB_BAR_RECONSTRUCTIONS_DETAILS = "tab_bar_reconstructions_details"
TAG_TEXT_RECONSTRUCTIONS_DETAILS_GENERATORS = "text_reconstructions_details_generators"
TAG_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTI = "button_reconstructions_details_export_fti"
TAG_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTIS = "button_reconstructions_details_export_ftis"
TAG_THEME_TABLE_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = "theme_reconstruction_details_initial_pitch_table"

SUF_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO = "_audio"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_PLOT_WINDOW = "_plot_window"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_SEPARATOR = "_separator"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_NO_DATA_MESSAGE = "_no_data_message"
SUF_RECONSTRUCTIONS_DETAILS_WINDOW = "_window"

LBL_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_FILE = "Reconstruct file"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_DIRECTORY = "Reconstruct directory"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_REFRESH_LIST = "Refresh reconstructions"
LBL_TREE_RECONSTRUCTIONS_BROWSER_RECONSTRUCTIONS = "Reconstructions"
LBL_RECONSTRUCTIONS_BROWSER_RECONSTRUCTIONS = "Reconstructions"
LBL_TEXT_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "Play audio source:"
LBL_BUTTON_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV = "Export reconstruction to WAV"
LBL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_ORIGINAL_AUDIO = "Original audio"
LBL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO = "Reconstruction"
LBL_PLOT_LABEL_RECONSTRUCTIONS_RECONSTRUCION_WAVEFORM = "Reconstruction waveform"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_RECONSTRUCTION_DETAILS = "Reconstruction details"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTI = "Export instrument to FTI"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTIS = "Export reconstruction as FTIs"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_COPY = "Copy"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_PITCH = "Pitch"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_HI_PITCH = "Hi-pitch"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_VOLUME = "Volume"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_ARPEGGIO = "Arpeggio"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_DUTY_CYCLE = "Duty cycle"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_GENERATORS = "Generators"
LBL_CONTEXT_ITEM_RECONSTRUCTIONS_BROWSER_LOAD_RECONSTRUCTION = "Load reconstructions"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_INITIAL_PERIOD = "Initial period:"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = "Initial pitch: "
MSG_RECONSTRUCTIONS_BROWSER_RECONSTRUCTION_FILE_NOT_FOUND = "The reconstruction file could not be found."
MSG_RECONSTRUCTIONS_BROWSER_RECONSTRUCTION_AUDIO_FILE_NOT_FOUND = (
    "The audio file of this reconstruction could not be found."
)
MSG_RECONSTRUCTIONS_BROWSER_FILE_LOAD_ERROR = "Failed to load reconstruction."
MSG_RECONSTRUCTIONS_BROWSER_INVALID_RECONSTRUCTION_VALUES = "Reconstruction contains invalid values."
MSG_RECONSTRUCTIONS_BROWSER_INVALID_RECONSTRUCTION_FILE = "Invalid reconstruction file."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV_SUCCESS = "Reconstruction rendered successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV_FAILED = "Reconstruction failed to save."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTI_SUCCESS = "Instrument saved successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTIS_SUCCESS = "Reconstruction instruments saved successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTI_FAILED = "Failed to export instrument as FTI."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTIS_FAILED = "Failed to export reconstruction as FTIs."
MSG_STATUS_RECONSTRUCTIONS_DETAILS_INPUT_PITCH_VALUE = (
    'CTRL + click to type value. Enter note name (e.g. "C-4") or MIDI value (72).'
)
MSG_STATUS_RECONSTRUCTIONS_DETAILS_INPUT_PERIOD_VALUE = (
    'CTRL + click to type value. Enter period name (e.g. "p508") or integer value (4).'
)
MSG_STATUS_RECONSTRUCTIONS_DETAILS_BAR = (
    "Click to change {instrument_feature}. Scroll to zoom horizontally. SHIFT + scroll to zoom vertically."
)
MSG_STATUS_RECONSTRUCTIONS_DETAILS_SEQUENCE = "Edit and press ENTER to change {instrument_feature}."
MSG_STATUS_RECONSTRUCTIONS_DETAILS_COPY_SEQUENCE = "Copy sequence to clipboard."
MSG_STATUS_RECONSTRUCTIONS_DETAILS_GENERATOR_TOGGLE = "Click to turn {on_or_off} {generator_name}."
MSG_STATUS_RECONSTRUCTIONS_DETAILS_GENERATOR_NOT_AVAILABLE = "{generator_name} is not available."

TTL_DIALOG_LOAD_RECONSTRUCTION = "Load reconstruction"
TTL_DIALOG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_STATUS = "Export status"
TTL_DIALOG_RECONSTRUCTIONS_RECONSTRUCTION_NOT_LOADED = "Reconstruction not loaded"
TTL_DIALOG_EXPORT_WAV = "Export WAV"
TTL_DIALOG_EXPORT_FTI = "Export FTI"

TPL_TAG_CHECKBOX_RECONSTRUCTIONS_RECONSTRUCTION_GENERATOR = "reconstruction_generator_{}"
TPL_TAG_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "reconstruction_audio_source_{}"
TPL_RECONSTRUCTIONS_BROWSER_INCOMPATIBLE_RECONSTRUCTION_FILE = "Incompatible reconstruction version: {}, expected {}."
TPL_TEXT_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = "Initial pitch: {} ({})"
TPL_TOOLTIP_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = "Enter the initial {} by name (e.g. {}) or value ({})."

DIM_TABLE_CELL_WIDTH_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH_LABEL = 160
DIM_TABLE_CELL_WIDTH_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH_DISPLAY = 28
DIM_TABLE_CELL_WIDTH_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH_BUTTON = 32

VAL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "selector"
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_ARPEGGIO_Y = -128.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_ARPEGGIO_Y = 127.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_PITCH_Y = -128.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_PITCH_Y = 127.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_VOLUME_Y = 0.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_VOLUME_Y = 15.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_DUTY_CYCLE_Y = 0.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_DUTY_CYCLE_Y = 3.0
VAL_TABLE_CELL_PADDING_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = (2, 2)
VAL_DELAY_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH_CHANGE = 0.075
VAL_TOOLTIP_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH_PERIOD_EXAMPLE = "p508"
VAL_TOOLTIP_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH_PITCH_EXAMPLE = "C-4"
VAL_PRIORITY_RECONSTRUCTIONS_BROWSER_ADD_HANDLER = 10
VAL_PRIORITY_RECONSTRUCTIONS_BROWSER_ADD_NODE = 9

COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_PITCH = (100, 200, 255, 255)
COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_VOLUME = (100, 255, 100, 255)
COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_ARPEGGIO = (255, 150, 100, 255)
COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_DUTY_CYCLE = (255, 200, 100, 255)
