TAG_RECONSTRUCTION_NOT_LOADED_DIALOG = "reconstruction_not_loaded_dialog"
TAG_PANEL_RECONSTRUCTIONS_BROWSER = "browser_panel"
TAG_TREE_RECONSTRUCTIONS_BROWSER = "browser_tree"
TAG_GROUP_RECONSTRUCTIONS_BROWSER_TREE = "browser_tree_group"
TAG_WINDOW_RECONSTRUCTIONS_BROWSER_TREE = "browser_tree_window"
TAG_GROUP_RECONSTRUCTIONS_BROWSER_CONTROLS = "browser_controls_group"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_REFRESH_RECONSTRUCTIONS = "browser_refresh_list_button"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_FILE = "browser_reconstruct_file_button"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_DIRECTORY = "browser_reconstruct_directory_button"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION = "reconstruction_panel"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION_PLAYER = "reconstruction_player_panel"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION_WAVEFORM = "reconstruction_waveform_display"
TAG_GROUP_RECONSTRUCTIONS_RECONSTRUCTION_GENERATORS = "reconstruction_generators_group"
TAG_GROUP_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "reconstruction_audio_source_group"
TAG_BUTTON_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV = "reconstruction_export_wav_button"
TAG_PANEL_RECONSTRUCTIONS_DETAILS = "reconstruction_details_panel"
TAG_TAB_BAR_RECONSTRUCTIONS_DETAILS = "reconstruction_details_tab_bar"
TAG_TEXT_RECONSTRUCTIONS_DETAILS_GENERATORS = "reconstruction_details_generators"
TAG_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTI = "reconstruction_export_fti_button"
TAG_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTIS = "reconstruction_export_ftis_button"

SUF_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO = "_audio"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_PLOT = "_plot"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_SEPARATOR = "_separator"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_NO_DATA_MESSAGE = "_no_data_message"
SUF_RECONSTRUCTIONS_DETAILS_WINDOW = "_window"

LBL_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_FILE = "Reconstruct file"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_DIRECTORY = "Reconstruct directory"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_REFRESH_LIST = "Refresh reconstructions"
LBL_TREE_RECONSTRUCTIONS_BROWSER_RECONSTRUCTIONS = "Reconstructions"
LBL_RECONSTRUCTIONS_BROWSER_RECONSTRUCTIONS = "Reconstructions"
LBL_TEXT_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "Play audio source:"
LBL_BUTTON_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV = "Export reconstruction to WAV"
LBL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_ORIGINAL_AUDIO = "Original audio"
LBL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO = "Reconstruction"
LBL_PLOT_LABEL_RECONSTRUCTIONS_RECONSTRUCION_WAVEFORM = "Reconstruction waveform"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_RECONSTRUCTION_DETAILS = "Reconstruction details"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTI = "Export instrument to FTI"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTIS = "Export reconstruction as FTIs"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_COPY = "Copy"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_PITCH = "Pitch"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_HI_PITCH = "Hi-pitch"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_VOLUME = "Volume"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_ARPEGGIO = "Arpeggio"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_DUTY_CYCLE = "Duty cycle"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_GENERATORS = "Generators"

MSG_RECONSTRUCTIONS_BROWSER_RECONSTRUCTION_FILE_NOT_FOUND = "The reconstruction file could not be found."
MSG_RECONSTRUCTIONS_BROWSER_RECONSTRUCTION_AUDIO_FILE_NOT_FOUND = (
    "The audio file of this reconstruction could not be found."
)
MSG_RECONSTRUCTIONS_BROWSER_FILE_LOAD_ERROR = "Failed to load reconstruction."
MSG_RECONSTRUCTIONS_BROWSER_INVALID_RECONSTRUCTION_VALUES = "Reconstruction contains invalid values."
MSG_RECONSTRUCTIONS_BROWSER_INVALID_RECONSTRUCTION_FILE = "Invalid reconstruction file."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV_SUCCESS = "Reconstruction rendered successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV_FAILED = "Reconstruction failed to save."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTI_SUCCESS = "Instrument saved successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTIS_SUCCESS = "Reconstruction instruments saved successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTI_FAILED = "Failed to export instrument as FTI."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTIS_FAILED = "Failed to export reconstruction as FTIs."

TTL_DIALOG_LOAD_RECONSTRUCTION = "Load reconstruction"
TTL_DIALOG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_STATUS = "Export status"
TTL_DIALOG_RECONSTRUCTIONS_RECONSTRUCTION_NOT_LOADED = "Reconstruction not loaded"
TTL_DIALOG_EXPORT_WAV = "Export WAV"
TTL_DIALOG_EXPORT_FTI = "Export FTI"

TPL_TAG_CHECKBOX_RECONSTRUCTIONS_RECONSTRUCTION_GENERATOR = "reconstruction_generator_{}"
TPL_TAG_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "reconstruction_audio_source_{}"
TPL_RECONSTRUCTIONS_BROWSER_INCOMPATIBLE_RECONSTRUCTION_FILE = "Incompatible reconstruction version: {}, expected {}."
TPL_TEXT_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = "Initial pitch: {} ({})"

VAL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "selector"
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_PITCH_Y = -128.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_PITCH_Y = 127.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_VOLUME_Y = 0.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_VOLUME_Y = 15.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MIN_DUTY_CYCLE_Y = 0.0
VAL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_MAX_DUTY_CYCLE_Y = 3.0

COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_PITCH = (100, 200, 255, 255)
COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_VOLUME = (100, 255, 100, 255)
COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_ARPEGGIO = (255, 150, 100, 255)
COL_BAR_PLOT_RECONSTRUCTIONS_DETAILS_DUTY_CYCLE = (255, 200, 100, 255)
