TAG_PANEL_SEQUENCER_BROWSER = "panel_sequencer_browser"
TAG_TREE_SEQUENCER_BROWSER = "tree_sequencer_browser"
TAG_GROUP_SEQUENCER_BROWSER_TREE = "group_sequencer_browser_tree"
TAG_WINDOW_SEQUENCER_BROWSER_TREE = "window_sequencer_browser_tree"
TAG_GROUP_SEQUENCER_BROWSER_CONTROLS = "group_sequencer_browser_controls"
TAG_BUTTON_SEQUENCER_BROWSER_REFRESH_RECONSTRUCTIONS = "button_sequencer_browser_refresh_reconstructions"

TAG_PANEL_SEQUENCER_GRID = "panel_sequencer_grid"
TAG_PANEL_SEQUENCER_GRID_PLAYER = "panel_sequencer_grid_player"
TAG_GROUP_SEQUENCER_GRID_MODULE_OPTIONS = "group_sequencer_grid_module_options"
TAG_INPUT_SEQUENCER_GRID_NES_FREQUENCY = "input_sequencer_grid_nes_frequency"
TAG_INPUT_SEQUENCER_GRID_TEMPO = "input_sequencer_grid_tempo"
TAG_INPUT_SEQUENCER_GRID_SPEED = "input_sequencer_grid_speed"
TAG_BUTTON_SEQUENCER_GRID_EXPORT_MODULE = "button_sequencer_grid_export_module"
TAG_TABLE_SEQUENCER_GRID_TRACKER = "table_sequencer_grid_tracker"
TAG_WINDOW_SEQUENCER_GRID_TRACKER = "window_sequencer_grid_tracker"

TAG_PANEL_SEQUENCER_SAMPLES = "panel_sequencer_instruments"
TAG_TABLE_SEQUENCER_SAMPLES = "table_sequencer_instruments"
TAG_WINDOW_SEQUENCER_SAMPLES = "window_sequencer_instruments"

LBL_BUTTON_SEQUENCER_BROWSER_REFRESH_LIST = "Refresh reconstructions"
LBL_TREE_SEQUENCER_BROWSER_RECONSTRUCTIONS = "Reconstructions"
LBL_SEQUENCER_BROWSER_RECONSTRUCTIONS = "Reconstructions"

LBL_TEXT_SEQUENCER_GRID_MODULE_OPTIONS = "Module options"
LBL_TEXT_SEQUENCER_GRID_NES_FREQUENCY = "NES frequency:"
LBL_TEXT_SEQUENCER_GRID_TEMPO = "Tempo:"
LBL_TEXT_SEQUENCER_GRID_SPEED = "Speed:"
LBL_BUTTON_SEQUENCER_GRID_EXPORT_MODULE = "Export as FamiTracker module"
LBL_TEXT_SEQUENCER_GRID_TRACKER = "Tracker"

LBL_TABLE_SEQUENCER_GRID_COLUMN_ROW = "Row"
LBL_TABLE_SEQUENCER_GRID_COLUMN_SAMPLE = "Sample"
LBL_TABLE_SEQUENCER_GRID_COLUMN_PULSE_1 = "Pulse 1"
LBL_TABLE_SEQUENCER_GRID_COLUMN_PULSE_2 = "Pulse 2"
LBL_TABLE_SEQUENCER_GRID_COLUMN_TRIANGLE = "Triangle"
LBL_TABLE_SEQUENCER_GRID_COLUMN_NOISE = "Noise"
LBL_TABLE_SEQUENCER_GRID_COLUMN_NOTE = "Note"
LBL_TABLE_SEQUENCER_GRID_COLUMN_VOLUME = "Vol"
LBL_TABLE_SEQUENCER_GRID_COLUMN_TRANSPOSE = "Transpose"

LBL_TEXT_SEQUENCER_SAMPLES = "Samples"
LBL_TABLE_SEQUENCER_SAMPLES_COLUMN_ID = "ID"
LBL_TABLE_SEQUENCER_SAMPLES_COLUMN_NAME = "Name"

MSG_SEQUENCER_BROWSER_RECONSTRUCTION_FILE_NOT_FOUND = "The reconstruction file could not be found."
MSG_SEQUENCER_BROWSER_FILE_LOAD_ERROR = "Failed to load reconstruction."

MSG_STATUS_SEQUENCER_BROWSER_SEARCH = "Search reconstructions"

TTL_DIALOG_EXPORT_MODULE = "Export FamiTracker module"
TTL_DIALOG_SEQUENCER_BROWSER_LOAD_RECONSTRUCTION = "Load reconstruction as instrument"

VAL_SEQUENCER_GRID_TEMPO_MIN = 32
VAL_SEQUENCER_GRID_TEMPO_MAX = 255
VAL_SEQUENCER_GRID_TEMPO_DEFAULT = 150

VAL_SEQUENCER_GRID_SPEED_MIN = 1
VAL_SEQUENCER_GRID_SPEED_MAX = 31
VAL_SEQUENCER_GRID_SPEED_DEFAULT = 6

VAL_SEQUENCER_GRID_TRACKER_ROWS = 64
VAL_SEQUENCER_GRID_TRACKER_ROW_HEIGHT = 20

DIM_TABLE_CELL_WIDTH_SEQUENCER_GRID_ROW = 30
DIM_TABLE_CELL_WIDTH_SEQUENCER_GRID_SAMPLE = 80
DIM_TABLE_CELL_WIDTH_SEQUENCER_GRID_GENERATOR = 80

DIM_TABLE_CELL_WIDTH_SEQUENCER_SAMPLES_ID = 40
DIM_TABLE_CELL_WIDTH_SEQUENCER_SAMPLES_NAME = -1

DIM_PANEL_WIDTH_SEQUENCER_INSTRUMENTS = 360

VAL_PRIORITY_SEQUENCER_BROWSER_ADD_NODE = 100
VAL_PRIORITY_SEQUENCER_BROWSER_ADD_HANDLER = 200
