TAG_WINDOW_SETTINGS_AUDIO = "audio_settings_window"
TAG_COMBO_SETTINGS_AUDIO_DEVICE = "audio_settings_device_combo"
TAG_COMBO_SETTINGS_AUDIO_SAMPLE_RATE = "audio_settings_sample_rate_combo"
TAG_GROUP_SETTINGS_AUDIO_DEVICE = "audio_settings_device_group"
TAG_GROUP_SETTINGS_AUDIO_SAMPLE_RATE = "audio_settings_sample_rate_group"
TAG_BUTTON_SETTINGS_AUDIO_APPLY = "audio_settings_apply_button"
TAG_BUTTON_SETTINGS_AUDIO_REFRESH = "audio_settings_refresh_button"

SUF_SETTINGS_AUDIO_HZ = " Hz"
SUF_SETTINGS_AUDIO_BIT = "-bit"

LBL_TEXT_SETTINGS_AUDIO_OUTPUT_DEVICE = "Output device"
LBL_TEXT_SETTINGS_AUDIO_SAMPLE_RATE = "Sample rate"
LBL_BUTTON_SETTINGS_AUDIO_APPLY = "Apply"
LBL_BUTTON_SETTINGS_AUDIO_REFRESH_DEVICES = "Refresh devices"

TTL_SETTINGS_AUDIO = "Audio settings"

DIM_WINDOW_WIDTH_SETTINGS_AUDIO = 600
DIM_WINDOW_HEIGHT_SETTINGS_AUDIO = 0
DIM_COMBO_WIDTH_SETTINGS_AUDIO = -1
DIM_TEXT_WIDTH_SETTINGS_AUDIO = 150
