# automatically generated by the FlatBuffers compiler, do not modify

# namespace: triangle

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBTriangleInstruction(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBTriangleInstruction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBTriangleInstruction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBTriangleInstruction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBTriangleInstruction
    def On(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBTriangleInstruction
    def Pitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0


def FBTriangleInstructionStart(builder):
    builder.StartObject(2)


def Start(builder):
    return FBTriangleInstructionStart(builder)


def FBTriangleInstructionAddOn(builder, on):
    builder.PrependBoolSlot(0, on, 0)


def AddOn(builder, on):
    return FBTriangleInstructionAddOn(builder, on)


def FBTriangleInstructionAddPitch(builder, pitch):
    builder.PrependInt32Slot(1, pitch, 0)


def AddPitch(builder, pitch):
    return FBTriangleInstructionAddPitch(builder, pitch)


def FBTriangleInstructionEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBTriangleInstructionEnd(builder)
