# automatically generated by the FlatBuffers compiler, do not modify

# namespace: collections

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBHistogram(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBHistogram()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBHistogram(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBHistogram
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBHistogram
    def Edges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # FBHistogram
    def EdgesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FBHistogram
    def EdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBHistogram
    def EdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FBHistogram
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # FBHistogram
    def ValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FBHistogram
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBHistogram
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def FBHistogramStart(builder):
    builder.StartObject(2)


def Start(builder):
    return FBHistogramStart(builder)


def FBHistogramAddEdges(builder, edges):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)


def AddEdges(builder, edges):
    return FBHistogramAddEdges(builder, edges)


def FBHistogramStartEdgesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartEdgesVector(builder, numElems):
    return FBHistogramStartEdgesVector(builder, numElems)


def FBHistogramAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)


def AddValues(builder, values):
    return FBHistogramAddValues(builder, values)


def FBHistogramStartValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartValuesVector(builder, numElems):
    return FBHistogramStartValuesVector(builder, numElems)


def FBHistogramEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBHistogramEnd(builder)
