# automatically generated by the FlatBuffers compiler, do not modify

# namespace: metadata

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBMetadata(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBMetadata
    def ApplicationName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBMetadata
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBMetadata
    def LibraryDataVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBMetadata
    def ReconstructionDataVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def FBMetadataStart(builder):
    builder.StartObject(4)


def Start(builder):
    return FBMetadataStart(builder)


def FBMetadataAddApplicationName(builder, applicationName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(applicationName), 0)


def AddApplicationName(builder, applicationName):
    return FBMetadataAddApplicationName(builder, applicationName)


def FBMetadataAddVersion(builder, version):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)


def AddVersion(builder, version):
    return FBMetadataAddVersion(builder, version)


def FBMetadataAddLibraryDataVersion(builder, libraryDataVersion):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(libraryDataVersion), 0)


def AddLibraryDataVersion(builder, libraryDataVersion):
    return FBMetadataAddLibraryDataVersion(builder, libraryDataVersion)


def FBMetadataAddReconstructionDataVersion(builder, reconstructionDataVersion):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(reconstructionDataVersion), 0)


def AddReconstructionDataVersion(builder, reconstructionDataVersion):
    return FBMetadataAddReconstructionDataVersion(builder, reconstructionDataVersion)


def FBMetadataEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBMetadataEnd(builder)
