dimensions:
  instruction_choice_height: 105
  instruction_choice_input_width: 220

values:
  float_precision: 4

colors:
  library: [220, 220, 220, 255]
  generator: [210, 232, 210, 255]
  group: [210, 232, 232, 255]
  instruction: [210, 210, 210, 255]
