samples_panel_width: 360
cell_padding: [3, 4]

order:
  height: 171
  position_column_width: 40

table_cells:
  row: 30
  sample: 80
  divider: 4
  generator: 80
  instrument_id: 40
  instrument_name: -1

tempo:
  min: 32
  max: 255
  default: 150

speed:
  min: 1
  max: 31
  default: 6

tracker:
  rows: 64
  row_height: 20
  page_size: 16
  subcolumn_widths:
    instrument: 26
    transpose: 30
    volume: 18

colors:
  pattern_highlight: "#ffffff40"
  cell_cursor: "#4488ff60"
  cursor_row: "#ffffff18"
  sample_column: "#22ccff18"
  sample_divider: "#22ccff24"
  order_column: "#1e2028"
  order_column_alternate: "#262834"
  subcolumns:
    instrument: "#ffffffff"
    transpose: "#a0a0a0ff"
    volume: "#64dc64ff"
