TAG_PANEL_INSTRUCTIONS_LIBRARY = "panel_instructions_library"
TAG_TEXT_INSTRUCTIONS_LIBRARY_STATUS = "text_instructions_library_status"
TAG_GROUP_INSTRUCTIONS_LIBRARY_CONTROLS = "group_instructions_library_controls"
TAG_BUTTON_INSTRUCTIONS_LIBRARY_GENERATE_LIBRARY = "button_instructions_library_generate_library"
TAG_BUTTON_INSTRUCTIONS_LIBRARY_REFRESH_LIBRARIES = "button_instructions_library_refresh_libraries"
TAG_PROGRESS_INSTRUCTIONS_LIBRARY = "progress_instructions_library"
TAG_TREE_INSTRUCTIONS_LIBRARY = "tree_instructions_library"
TAG_GROUP_INSTRUCTIONS_LIBRARY_TREE = "group_instructions_library_tree"
TAG_WINDOW_INSTRUCTIONS_LIBRARY_TREE = "window_instructions_library_tree"
TAG_DIALOG_INSTRUCTIONS_LIBRARY_LIBRARY_NOT_LOADED = "dialog_instructions_library_library_not_loaded"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION = "panel_instructions_instruction"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_PLAYER = "panel_instructions_instruction_player"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_WAVEFORM = "panel_instructions_instruction_waveform"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_SPECTRUM = "panel_instructions_instruction_spectrum"
TAG_TEXT_INSTRUCTIONS_DETAILS_INFO = "text_instructions_details_info"
TAG_PANEL_INSTRUCTIONS_DETAILS = "panel_instructions_details"
TAG_TABLE_INSTRUCTIONS_DETAILS_GENERAL = "table_instructions_details_general"
TAG_TABLE_INSTRUCTIONS_DETAILS_PARAMETERS = "table_instructions_details_parameters"
TAG_HEADER_INSTRUCTIONS_DETAILS_GENERAL = "header_instructions_details_general"
TAG_HEADER_INSTRUCTIONS_DETAILS_PARAMETERS = "header_instructions_details_parameters"
TAG_THEME_INSTRUCTIONS_LIBRARY_LIBRARY = "theme_instructions_library_library"
TAG_THEME_INSTRUCTIONS_LIBRARY_GENERATOR = "theme_instructions_library_generator"
TAG_THEME_INSTRUCTIONS_LIBRARY_GROUP = "theme_instructions_library_group"
TAG_THEME_INSTRUCTIONS_LIBRARY_INSTRUCTION = "theme_instructions_library_instruction"
TAG_INPUT_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_PULSE_PITCH = (
    "input_instructions_details_instructions_choice_pulse_pitch"
)
TAG_INPUT_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_PULSE_VOLUME = (
    "input_instructions_details_instructions_choice_pulse_volume"
)
TAG_INPUT_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_PULSE_DUTY_CYCLE = (
    "input_instructions_details_instructions_choice_pulse_duty_cycle"
)
TAG_INPUT_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_TRIANGLE_PITCH = (
    "input_instructions_details_instructions_choice_triangle_pitch"
)
TAG_INPUT_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_NOISE_VOLUME = (
    "input_instructions_details_instructions_choice_noise_volume"
)
TAG_INPUT_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_NOISE_PERIOD = (
    "input_instructions_details_instructions_choice_noise_period"
)
TAG_CHECKBOX_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE_NOISE_SHORT = (
    "checkbox_instructions_details_instructions_choice_noise_short"
)
TAG_GROUP_INSTRUCTIONS_DETAILS_INSTRUCTIONS_CHOICE = "group_instructions_details_instructions_choice"
TAG_GROUP_INSTRUCTIONS_DETAILS_TABLES = "group_instructions_details_tables"

SUF_GRAPH_INSTRUCTIONS_INSTRUCTION_WAVEFORM_WINDOW = "_waveform_window"
SUF_GRAPH_INSTRUCTIONS_INSTRUCTIONS_SPECTRUM_WINDOW = "_spectrum_window"
SUF_INSTRUCTION_DETAILS_TABLE = "_table"
