SUF_PLAYER_PLAY = ".play"
SUF_PLAYER_PAUSE = ".pause"
SUF_PLAYER_STOP = ".stop"
SUF_PLAYER_POSITION = ".position"
SUF_PLAYER_FOLLOW = ".follow"
SUF_PLAYER_CONTROLS_GROUP = ".controls_group"
SUF_PLAYER_NO_AUDIO_POPUP = ".no_audio_popup"
SUF_PLAYER_ERROR_POPUP = ".error_popup"
