SUF_PLAYER_PLAY = "_play"
SUF_PLAYER_PAUSE = "_pause"
SUF_PLAYER_STOP = "_stop"
SUF_PLAYER_POSITION = "_position"
SUF_PLAYER_CONTROLS_GROUP = "_controls_group"
SUF_PLAYER_NO_AUDIO_POPUP = "_no_audio_popup"
SUF_PLAYER_ERROR_POPUP = "_error_popup"
