from sampletones_application.categories.hierarchy import Page, Panel, Widget
from sampletones_application.categories.key import TagName

PRE_RECONSTRUCTION_GENERATOR = "reconstruction.generator."

TAG_RECONSTRUCTIONS_RECONSTRUCTION_DIALOG_NOT_LOADED = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.DIALOG,
    "not_loaded",
)
TAG_RECONSTRUCTIONS_BROWSER_PANEL = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.PANEL,
    "browser",
)
TAG_RECONSTRUCTIONS_BROWSER_TREE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.TREE,
    "browser",
)
TAG_RECONSTRUCTIONS_BROWSER_GROUP_TREE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.GROUP,
    "tree",
)
TAG_RECONSTRUCTIONS_BROWSER_WINDOW_TREE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.WINDOW,
    "tree",
)
TAG_RECONSTRUCTIONS_BROWSER_GROUP_CONTROLS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.GROUP,
    "controls",
)
TAG_RECONSTRUCTIONS_BROWSER_BUTTON_REFRESH_RECONSTRUCTIONS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.BUTTON,
    "refresh_reconstructions",
)
TAG_RECONSTRUCTIONS_BROWSER_BUTTON_RECONSTRUCT_FILE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.BUTTON,
    "reconstruct_file",
)
TAG_RECONSTRUCTIONS_BROWSER_BUTTON_RECONSTRUCT_DIRECTORY = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.BUTTON,
    "reconstruct_directory",
)
TAG_RECONSTRUCTIONS_BROWSER_GROUP_RECONSTRUCT = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.GROUP,
    "reconstruct",
)
TAG_RECONSTRUCTIONS_BROWSER_TOOLTIP_RECONSTRUCT = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.TOOLTIP,
    "reconstruct",
)
TAG_RECONSTRUCTIONS_BROWSER_DIALOG_REMOVE_RECONSTRUCTION_CONFIRMATION = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.DIALOG,
    "remove_reconstruction_confirmation",
)
TAG_RECONSTRUCTIONS_BROWSER_DIALOG_REMOVE_DIRECTORY_CONFIRMATION = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.DIALOG,
    "remove_directory_confirmation",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PANEL_PLAYER = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "reconstruction_player",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PANEL_WAVEFORM = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "reconstruction_waveform",
)
TAG_RECONSTRUCTIONS_AUDIO_PANEL = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "audio",
)
TAG_RECONSTRUCTIONS_PLOT_PANEL = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "plot",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_GROUP_GENERATORS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.GROUP,
    "generators",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_GROUP_AUDIO_SOURCE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.GROUP,
    "audio_source",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_RADIO_AUDIO_SOURCE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.RADIO,
    "audio_source",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PATH_RECONSTRUCTION_FILE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PATH,
    "reconstruction_file",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PATH_ORIGINAL_AUDIO = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PATH,
    "original_audio",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_PANEL = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.PANEL,
    "instruments",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_TABS_BAR = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.TABS,
    "bar",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_BUTTON_EXPORT_INSTRUMENT = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.BUTTON,
    "export_instrument",
)

SUF_RECONSTRUCTIONS_INSTRUMENTS_NO_DATA_MESSAGE = ".no_data_message"
SUF_RECONSTRUCTIONS_INSTRUMENTS_WINDOW = ".window"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_AUTOSCALE = ".autoscale"
