from typing import Final

CONFIG: Final = "config"
METADATA: Final = "metadata"
GENERATION: Final = "generation"
GENERATORS: Final = "generators"

SPECTRUM_METHOD: Final = "spectrum_method"
TRANSFORMATION_GAMMA: Final = "transformation_gamma"
ITEMS: Final = "items"
FRAGMENT: Final = "fragment"
FEATURE: Final = "feature"
EDGES: Final = "edges"
VALUES: Final = "values"

AUDIO_FILEPATH: Final = "audio_filepath"
INSTRUCTIONS_DATA: Final = "instructions_data"
APPROXIMATIONS_DATA: Final = "approximations_data"
RECONSTRUCTION_DATA_VERSION: Final = "reconstruction_data_version"

STEMS_DATA: Final = "stems_data"
ENTRIES: Final = "entries"
ID: Final = "id"
BENDS: Final = "bends"
SETTINGS: Final = "settings"
HIERARCHY: Final = "hierarchy"
LEVELS: Final = "levels"
MODE: Final = "mode"
CHANNEL_CAP: Final = "channel_cap"
DRIVES: Final = "drives"
ASSIGNMENTS: Final = "assignments"
STEM_IDS: Final = "stem_ids"
INSTRUCTIONS: Final = "instructions"

CHANNELS: Final = "channels"
DRIVE: Final = "drive"
MIXER: Final = "mixer"
FINAL_REGENERATION: Final = "final_regeneration"
CALCULATION: Final = "calculation"
FAST_DIFFERENCE: Final = "fast_difference"
GENERATOR: Final = "generator"
NAME: Final = "name"

SONG: Final = "song"
PATTERNS: Final = "patterns"
ROWS: Final = "rows"
COMMAND: Final = "command"

CHANNEL_NAME: Final = "channel_name"
GENERATOR_NAME: Final = "generator_name"

SAMPLES: Final = "samples"
VOICES: Final = "voices"
KIND: Final = "kind"
KIND_SAMPLE: Final = "sample"
LOOP_POINT: Final = "loop_point"
SAMPLE_ID: Final = "sample_id"
VOICE_ID: Final = "voice_id"
