from typing import Final

CONFIG: Final = "config"
METADATA: Final = "metadata"
GENERATION: Final = "generation"
GENERATORS: Final = "generators"

AUDIO_FILEPATH: Final = "audio_filepath"
INSTRUCTIONS_DATA: Final = "instructions_data"
APPROXIMATION: Final = "approximation"
APPROXIMATIONS_DATA: Final = "approximations_data"
RECONSTRUCTION_DATA_VERSION: Final = "reconstruction_data_version"

STEMS_DATA: Final = "stems_data"
ENTRIES: Final = "entries"
ID: Final = "id"
BENDS: Final = "bends"
SETTINGS: Final = "settings"
HIERARCHY: Final = "hierarchy"
LEVELS: Final = "levels"
MODE: Final = "mode"
CHANNEL_CAP: Final = "channel_cap"
DRIVES: Final = "drives"
ASSIGNMENTS: Final = "assignments"
STEM_IDS: Final = "stem_ids"
INSTRUCTIONS: Final = "instructions"
INSTRUCTION: Final = "instruction"
UNION_DATA: Final = "_data"
ON: Final = "on"
SOURCES: Final = "sources"
STEM_ID: Final = "stem_id"
PATH: Final = "path"

CHANNELS: Final = "channels"
DRIVE: Final = "drive"
MIXER: Final = "mixer"
GENERATOR: Final = "generator"
NAME: Final = "name"

SONG: Final = "song"
PATTERNS: Final = "patterns"
ROWS: Final = "rows"
COMMAND: Final = "command"

CHANNEL_NAME: Final = "channel_name"
GENERATOR_NAME: Final = "generator_name"

SAMPLES: Final = "samples"
VOICES: Final = "voices"
KIND: Final = "kind"
KIND_SAMPLE: Final = "sample"
LOOP_POINT: Final = "loop_point"
SAMPLE_ID: Final = "sample_id"
VOICE_ID: Final = "voice_id"
