from sampletones_application.categories.abstract import AbstractElement


class DialogElements(AbstractElement):
    OK = "ok"
    EXIT = "exit"
    DISCARD = "discard"
    CLOSE = "close"
    SAVE = "save"
    CANCEL = "cancel"
    COPIED = "copied"
    YES = "yes"
    NO = "no"
    UNTITLED = "untitled"
    REMOVE = "remove"
    CHANGE_AND_RETUNE = "change_and_retune"
    DONT_ASK_AGAIN = "dont_ask_again"
    ADD_ANYWAY = "add_anyway"


class TracebackElements(AbstractElement):
    COPY = "copy"
    SHOW = "show"
    HIDE = "hide"


class TreeElements(AbstractElement):
    ROOT = "root"
    SEARCH = "search"
    FILTER = "filter"
    CLEAR_SEARCH = "clear_search"
    FAVORITES_ONLY = "favorites_only"


class ContextElements(AbstractElement):
    PLAY = "play"
    CUT = "cut"
    COPY = "copy"
    PASTE = "paste"
    DELETE = "delete"
    MARK_AS_FAVORITE = "mark_as_favorite"
    UNMARK_AS_FAVORITE = "unmark_as_favorite"
    COPY_FILENAME = "copy_filename"
    COPY_PATH = "copy_path"
    OPEN_IN_EXPLORER = "open_in_explorer"
    ADD_TO_SEQUENCER = "add_to_sequencer"
    REPLACE_SAMPLE = "replace_sample"
    LOCATE_ORIGINAL_AUDIO = "locate_original_audio"
    TRIANGLE = "triangle"
    PULSE_1 = "pulse_1"
    PULSE_2 = "pulse_2"
    NOISE = "noise"
    SAMPLE_SIZE = "sample_size"
    INSTRUMENT_SIZE = "instrument_size"
    SIZE_BYTES = "size_bytes"


class StemsElements(AbstractElement):
    """The vocabulary of a stems list, shared by every card that draws one."""

    LEVEL_CAPTION = "level_caption"
    REMOVE = "remove"
    DRAG_TOOLTIP = "drag_tooltip"
    INERT_TOOLTIP = "inert_tooltip"
    MISSING_TOOLTIP = "missing_tooltip"
    UNOFFERED_TOOLTIP = "unoffered_tooltip"
    STATUS_ROW_DRAG = "status_row_drag"
    STATUS_ROW_REVEAL = "status_row_reveal"
    STATUS_MASTER = "status_master"
    STATUS_CHANNEL = "status_channel"
    STATUS_CHANNEL_MUTED = "status_channel_muted"
    STATUS_REMOVE = "status_remove"


class NodeDetailElements(AbstractElement):
    SAMPLE_RATE = "detail_sample_rate"
    NES_FREQUENCY = "detail_nes_frequency"
    CHANNELS = "detail_channels"
    SPECTRUM_METHOD = "detail_spectrum_method"
    TRANSFORMATION_GAMMA = "detail_transformation_gamma"
    WINDOW_SIZE = "detail_window_size"
    CONFIGURATION = "detail_configuration"


class MenuElements(AbstractElement):
    GROUP_FILE = "group_file"
    ITEM_FILE_NEW_PROJECT = "item_file_new_project"
    ITEM_FILE_OPEN_PROJECT = "item_file_open_project"
    ITEM_FILE_SAVE_PROJECT = "item_file_save_project"
    ITEM_FILE_SAVE_PROJECT_AS = "item_file_save_project_as"
    ITEM_FILE_PROJECT_PROPERTIES = "item_file_project_properties"
    GROUP_FILE_EXPORT = "group_file_export"
    ITEM_FILE_EXPORT_FAMITRACKER = "item_file_export_famitracker"
    ITEM_FILE_EXPORT_BITPHASE = "item_file_export_bitphase"
    ITEM_FILE_RENDER_SONG = "item_file_render_song"
    ITEM_FILE_CLOSE_PROJECT = "item_file_close_project"
    ITEM_FILE_EXIT = "item_file_exit"
    GROUP_EDIT = "group_edit"
    ITEM_EDIT_UNDO = "item_edit_undo"
    ITEM_EDIT_REDO = "item_edit_redo"
    GROUP_RECONSTRUCTION = "group_reconstruction"
    ITEM_RECONSTRUCTION_RECONSTRUCT_FILE = "item_reconstruction_reconstruct_file"
    ITEM_RECONSTRUCTION_RECONSTRUCT_DIRECTORY = "item_reconstruction_reconstruct_directory"
    ITEM_RECONSTRUCTION_LOAD_GENERATION_SETTINGS = "item_reconstruction_load_generation_settings"
    ITEM_RECONSTRUCTION_SAVE_GENERATION_SETTINGS = "item_reconstruction_save_generation_settings"
    ITEM_RECONSTRUCTION_OPEN = "item_reconstruction_open"
    ITEM_RECONSTRUCTION_SAVE = "item_reconstruction_save"
    ITEM_RECONSTRUCTION_SAVE_AS = "item_reconstruction_save_as"
    ITEM_RECONSTRUCTION_CLOSE = "item_reconstruction_close"
    ITEM_RECONSTRUCTION_EXPORT_WAV = "item_reconstruction_export_wav"
    GROUP_RECONSTRUCTION_EXPORT_INSTRUMENTS = "group_reconstruction_export_instruments"
    ITEM_RECONSTRUCTION_EXPORT_INSTRUMENTS_FAMITRACKER = "item_reconstruction_export_instruments_famitracker"
    ITEM_RECONSTRUCTION_EXPORT_INSTRUMENTS_BITPHASE_PRESET = "item_reconstruction_export_instruments_bitphase_preset"
    ITEM_RECONSTRUCTION_EXPORT_INSTRUMENTS_NSF = "item_reconstruction_export_instruments_nsf"
    GROUP_PLAYBACK = "group_playback"
    ITEM_PLAYBACK_PLAY = "item_playback_play"
    ITEM_PLAYBACK_PAUSE = "item_playback_pause"
    ITEM_PLAYBACK_RESUME = "item_playback_resume"
    ITEM_PLAYBACK_PLAY_FROM_START = "item_playback_play_from_start"
    ITEM_PLAYBACK_PLAY_FROM_FRAME = "item_playback_play_from_frame"
    ITEM_PLAYBACK_STOP = "item_playback_stop"
    ITEM_PLAYBACK_AUTOPLAY = "item_playback_autoplay"
    GROUP_PLAYBACK_FOLLOW = "group_playback_follow"
    ITEM_PLAYBACK_FOLLOW_ROWS = "item_playback_follow_rows"
    ITEM_PLAYBACK_FOLLOW_PATTERNS = "item_playback_follow_patterns"
    ITEM_PLAYBACK_FOLLOW_OFF = "item_playback_follow_off"
    ITEM_PLAYBACK_LOOP_SONG = "item_playback_loop_song"
    GROUP_PLAYBACK_CHANNELS = "group_playback_channels"
    ITEM_PLAYBACK_UNMUTE_ALL_CHANNELS = "item_playback_unmute_all_channels"
    ITEM_PLAYBACK_AUDIO_SETTINGS = "item_playback_audio_settings"
    GROUP_VIEW = "group_view"
    ITEM_VIEW_SHOW_ADVANCED_SETTINGS = "item_view_show_advanced_settings"
    ITEM_VIEW_FULLSCREEN = "item_view_fullscreen"
    GROUP_VIEW_AUTO_EXPAND_FAVORITES = "group_view_auto_expand_favorites"
    ITEM_VIEW_AUTO_EXPAND_FAVORITE_RECONSTRUCTIONS = "item_view_auto_expand_favorite_reconstructions"
    ITEM_VIEW_AUTO_EXPAND_FAVORITE_DIRECTORIES = "item_view_auto_expand_favorite_directories"
    ITEM_VIEW_DISPLAY_SETTINGS = "item_view_display_settings"
    ITEM_VIEW_KEYBOARD_SETTINGS = "item_view_keyboard_settings"
    GROUP_HELP = "group_help"
    ITEM_HELP_ABOUT = "item_help_about"
    TAB_MAIN = "tab_main"
    TAB_INSTRUCTIONS = "tab_instructions"
    TAB_RECONSTRUCTION = "tab_reconstruction"
    TAB_SEQUENCER = "tab_sequencer"


class StatusElements(AbstractElement):
    PATH = "path"
    NODE_RECONSTRUCTION_NO_AUTOPLAY = "node_reconstruction_no_autoplay"
    NODE_RECONSTRUCTION = "node_reconstruction"
    NODE_LIBRARY = "node_library"
    TREE_SEARCH = "tree_search"
    CLEAR_SEARCH = "clear_search"
    FAVORITES_ONLY = "favorites_only"
    INPUT = "input"
    COMBO = "combo"
    NODE_DIRECTORY = "node_directory"
    RETUNING_SAMPLES = "retuning_samples"


class PlayerElements(AbstractElement):
    PLAY = "play"
    PAUSE = "pause"
    RESUME = "resume"
    STOP = "stop"
    AUDIO_PLAYBACK_ERROR = "audio_playback_error"


class GraphElements(AbstractElement):
    WAVEFORM_ORIGINAL = "waveform_original"
    WAVEFORM_RECONSTRUCTION = "waveform_reconstruction"
    WAVEFORM_TIME_AXIS = "waveform_time_axis"
    WAVEFORM_AMPLITUDE_AXIS = "waveform_amplitude_axis"
    WAVEFORM_SAMPLE_NAME = "waveform_sample_name"
    SPECTRUM_X_AXIS = "spectrum_x_axis"
    SPECTRUM_FREQUENCY_AXIS = "spectrum_frequency_axis"
    SPECTRUM_NAME = "spectrum_name"
    BAR_DISPLAY = "bar_display"
    SPECTRUM_NAVIGATION = "spectrum_navigation"
    WAVEFORM_NAVIGATION = "waveform_navigation"
    WAVEFORM_REGENERATING = "waveform_regenerating"


class GlobalMessageElements(AbstractElement):
    TREE_NO_RESULTS = "tree_no_results"
    TREE_NO_FAVORITES = "tree_no_favorites"
    INVALID_METADATA_ERROR = "invalid_metadata_error"
    RECONSTRUCTION_NO_DATA = "reconstruction_no_data"
    RECONSTRUCTION_SAVED_SUCCESSFULLY = "reconstruction_saved_successfully"
    RECONSTRUCTION_SAVE_FAILED = "reconstruction_save_failed"
    CONFIG_SAVE_FAILED = "config_save_failed"
    EXIT_CONVERSION_IN_PROGRESS = "exit_conversion_in_progress"
    EXIT_LIBRARY_GENERATION_IN_PROGRESS = "exit_library_generation_in_progress"
    EXIT_UNSAVED_RECONSTRUCTION = "exit_unsaved_reconstruction"
    CLOSE_UNSAVED_RECONSTRUCTION = "close_unsaved_reconstruction"
    LOAD_UNSAVED_RECONSTRUCTION = "load_unsaved_reconstruction"
    PROJECT_SAVED_SUCCESSFULLY = "project_saved_successfully"
    PROJECT_SAVE_FAILED = "project_save_failed"
    PROJECT_EXPORTED_SUCCESSFULLY = "project_exported_successfully"
    PROJECT_EXPORT_FAILED = "project_export_failed"
    BITPHASE_PROJECT_EXPORTED_SUCCESSFULLY = "bitphase_project_exported_successfully"
    BITPHASE_PROJECT_EXPORT_FAILED = "bitphase_project_export_failed"
    NEW_UNSAVED_PROJECT = "new_unsaved_project"
    OPEN_UNSAVED_PROJECT = "open_unsaved_project"
    CLOSE_UNSAVED_PROJECT = "close_unsaved_project"
    NEW_OPEN_PROJECT = "new_open_project"
    OPEN_OPEN_PROJECT = "open_open_project"
    EXIT_UNSAVED_PROJECT = "exit_unsaved_project"
    CONFIGURATION_SAVED_SUCCESSFULLY = "configuration_saved_successfully"
    CONFIGURATION_LOADED_SUCCESSFULLY = "configuration_loaded_successfully"
    CONFIGURATION_LOAD_ERROR = "configuration_load_error"
    CONFIGURATION_INVALID_ERROR = "configuration_invalid_error"
    CONFIGURATION_PARSE_ERROR = "configuration_parse_error"
    CONFIGURATION_RECOVERY_EARLIER_VERSION = "configuration_recovery_earlier_version"
    CONFIGURATION_RECOVERY_LIST_HEADER = "configuration_recovery_list_header"
    CONFIGURATION_RECOVERY_PATH_PREFIX = "configuration_recovery_path_prefix"
    AUDIO_PLAYBACK_ERROR = "audio_playback_error"
    NO_PROJECT_OPEN = "no_project_open"
    REMOVE_SAMPLE = "remove_sample"
    CHANGE_NES_FREQUENCY = "change_nes_frequency"
    FREQUENCY_MISMATCH = "frequency_mismatch"
    OPERATION_IN_PROGRESS = "operation_in_progress"
    ABOUT_DESCRIPTION = "about_description"


class GlobalDialogTitleElements(AbstractElement):
    MAIN_WINDOW = "main_window"
    SAVE_CONFIG = "save_config"
    LOAD_CONFIG = "load_config"
    CONFIGURATION_RECOVERY = "configuration_recovery"
    ERROR = "error"
    CONFIG_STATUS = "config_status"
    FILE_NOT_FOUND = "file_not_found"
    RECONSTRUCT_FILE = "reconstruct_file"
    RECONSTRUCT_DIRECTORY = "reconstruct_directory"
    EXIT_CONFIRMATION = "exit_confirmation"
    SAVE_RECONSTRUCTION = "save_reconstruction"
    RECONSTRUCTION_SAVED = "reconstruction_saved"
    CLOSE_UNSAVED_RECONSTRUCTION = "close_unsaved_reconstruction"
    LOAD_UNSAVED_RECONSTRUCTION = "load_unsaved_reconstruction"
    SAVE_PROJECT = "save_project"
    PROJECT_SAVED = "project_saved"
    EXPORT_MODULE = "export_module"
    EXPORT_BITPHASE_PROJECT = "export_bitphase_project"
    PROJECT_EXPORTED = "project_exported"
    NEW_UNSAVED_PROJECT = "new_unsaved_project"
    OPEN_UNSAVED_PROJECT = "open_unsaved_project"
    CLOSE_UNSAVED_PROJECT = "close_unsaved_project"
    NO_PROJECT_OPEN = "no_project_open"
    REMOVE_SAMPLE = "remove_sample"
    CHANGE_NES_FREQUENCY = "change_nes_frequency"
    FREQUENCY_MISMATCH = "frequency_mismatch"
    ABOUT = "about"


class FileFilterElements(AbstractElement):
    PROJECT = "project"
    RECONSTRUCTION = "reconstruction"
    MODULE = "module"
    FAMITRACKER_INSTRUMENT = "famitracker_instrument"
    BITPHASE_PROJECT = "bitphase_project"
    BITPHASE_PRESET = "bitphase_preset"
    NSF = "nsf"
    CONFIG = "config"
    AUDIO = "audio"
    WAVE = "wave"


class GlobalTemplateElements(AbstractElement):
    TIME_ESTIMATION = "time_estimation"
    CONFIGURATION_RECOVERY_INTRO = "configuration_recovery_intro"
    FPS = "fps"
    ABOUT_AUTHOR = "about_author"
    EXPAND = "expand"
    COLLAPSE = "collapse"
    ON = "on"
    OFF = "off"


class GlobalPitchElements(AbstractElement):
    PITCH_NAME = "pitch_name"
    PERIOD_NAME = "period_name"
    PITCH_EXAMPLE = "pitch_example"
    PERIOD_EXAMPLE = "period_example"
