from sampletones_application.categories.abstract import AbstractElement


class InstructionsLibraryElements(AbstractElement):
    GENERATE_LIBRARY_BUTTON = "generate_library_button"
    REGENERATE_LIBRARY_BUTTON = "regenerate_library_button"
    REFRESH_LIBRARIES_BUTTON = "refresh_libraries_button"
    LIBRARIES_TEXT = "libraries_text"
    AVAILABLE_LIBRARIES_TEXT = "available_libraries_text"
    LOAD_LIBRARY_NODE = "load_library_node"
    LIBRARIES_NODE = "libraries_node"
    CONTEXT_LOAD_GENERATOR = "context_load_generator"
    CONTEXT_LOAD_LIBRARY = "context_load_library"
    STATUS_DISPLAY_ERROR = "status_display_error"
    STATUS_GENERATING = "status_generating"
    STATUS_SAVING = "status_saving"
    STATUS_GENERATION_SUCCESS = "status_generation_success"
    STATUS_LOADING = "status_loading"
    STATUS_WINDOW_NOT_AVAILABLE = "status_window_not_available"
    STATUS_GENERATION_CANCELLED = "status_generation_cancelled"
    STATUS_GENERATION_FAILED = "status_generation_failed"
    STATUS_FILE_NOT_FOUND = "status_file_not_found"
    STATUS_FILE_LOAD_ERROR = "status_file_load_error"
    STATUS_LOAD_ERROR = "status_load_error"
    STATUS_INVALID_DATA = "status_invalid_data"
    STATUS_INVALID_DATA_VALUES = "status_invalid_data_values"
    STATUS_DESERIALIZATION_ERROR = "status_deserialization_error"
    STATUS_NODE_GENERATOR = "status_node_generator"
    STATUS_NODE_LIBRARY = "status_node_library"
    LIBRARY_NOT_LOADED_DIALOG = "library_not_loaded_dialog"
    GENERATION_STATUS_DIALOG = "generation_status_dialog"
    GENERATION_PROGRESS_TEMPLATE = "generation_progress_template"
    LIBRARY_NOT_EXISTS_TEMPLATE = "library_not_exists_template"
    LIBRARY_EXISTS_TEMPLATE = "library_exists_template"
    LIBRARY_LOADED_TEMPLATE = "library_loaded_template"
    INCOMPATIBLE_VERSION_TEMPLATE = "incompatible_version_template"


class InstructionPanelElements(AbstractElement):
    WAVEFORM_LABEL = "waveform_label"
    SPECTRUM_LABEL = "spectrum_label"


class InstructionsDetailsElements(AbstractElement):
    DETAILS_TEXT = "details_text"
    PARAMETERS_TEXT = "parameters_text"
    GENERAL_TEXT = "general_text"
    CELL_NES_FREQUENCY = "cell_nes_frequency"
    CELL_GENERATOR = "cell_generator"
    CELL_NAME = "cell_name"
    CELL_FREQUENCY = "cell_frequency"
    CELL_DUTY_CYCLE = "cell_duty_cycle"
    CELL_NO_FREQUENCY = "cell_no_frequency"
    CELL_SAMPLE_LENGTH = "cell_sample_length"
    CELL_SAMPLES_SUFFIX = "cell_samples_suffix"
    WINDOW_PULSE_PITCH = "window_pulse_pitch"
    WINDOW_PULSE_VOLUME = "window_pulse_volume"
    WINDOW_PULSE_DUTY_CYCLE = "window_pulse_duty_cycle"
    WINDOW_NOISE_PERIOD = "window_noise_period"
    WINDOW_NOISE_VOLUME = "window_noise_volume"
    WINDOW_NOISE_SHORT = "window_noise_short"
    WINDOW_TRIANGLE_PITCH = "window_triangle_pitch"
    FREQUENCY_TEMPLATE = "frequency_template"
    PITCH_TEMPLATE = "pitch_template"
    PERIOD_TEMPLATE = "period_template"
    DUTY_CYCLE_TEMPLATE = "duty_cycle_template"
    NO_INSTRUCTION_SELECTED = "no_instruction_selected"
