from sampletones_application.categories.abstract import AbstractElement


class ExplorerElements(AbstractElement):
    SECTION = "section"
    REFRESH_BUTTON = "refresh_button"
    CONTEXT_LOAD_RECONSTRUCTION = "context_load_reconstruction"
    CONTEXT_LOAD_LIBRARY = "context_load_library"
    CONTEXT_RECONSTRUCT_FILE = "context_reconstruct_file"
    CONTEXT_RECONSTRUCT_DIRECTORY = "context_reconstruct_directory"
    CONTEXT_SET_LIBRARY_DIRECTORY = "context_set_library_directory"
    CONTEXT_SET_OUTPUT_DIRECTORY = "context_set_output_directory"
    STATUS_REFRESH = "status_refresh"
    STATUS_NODE_AUDIO_NO_AUTOPLAY = "status_node_audio_no_autoplay"
    STATUS_NODE_AUDIO = "status_node_audio"
    STATUS_NODE_LIBRARY = "status_node_library"
    CONVERTER_RUNNING_MSG = "converter_running_msg"
    CONVERTER_RUNNING_DIALOG = "converter_running_dialog"


class ConfigPanelElements(AbstractElement):
    SECTION = "section"
    SECTION_LIBRARY = "section_library"
    CHECKBOX_NORMALIZE = "checkbox_normalize"
    CHECKBOX_QUANTIZE = "checkbox_quantize"
    INPUT_SAMPLE_RATE = "input_sample_rate"
    INPUT_NES_FREQUENCY = "input_nes_frequency"
    TOOLTIP_NORMALIZE = "tooltip_normalize"
    TOOLTIP_QUANTIZE = "tooltip_quantize"
    TOOLTIP_SAMPLE_RATE = "tooltip_sample_rate"
    TOOLTIP_NES_FREQUENCY = "tooltip_nes_frequency"


class ReconstructorElements(AbstractElement):
    SECTION_CHANNELS = "section_channels"
    SECTION_SETTINGS = "section_settings"
    SLIDER_DRIVE = "slider_drive"
    TOOLTIP_DRIVE = "tooltip_drive"


class ConverterElements(AbstractElement):
    SECTION = "section"
    CLOSE_BUTTON = "close_button"
    CANCEL_BUTTON = "cancel_button"
    LOAD_BUTTON = "load_button"
    OPEN_BUTTON = "open_button"
    STOP_BUTTON = "stop_button"
    CONTINUE_BUTTON = "continue_button"
    CONVERT_SAMPLE_BUTTON = "convert_sample_button"
    CONVERT_DIRECTORY_BUTTON = "convert_directory_button"
    STATUS_CONVERT = "status_convert"
    STATUS_CANCEL = "status_cancel"
    STATUS_ERROR = "status_error"
    STATUS_RECONSTRUCTION_COMPLETED = "status_reconstruction_completed"
    STATUS_NO_FILES = "status_no_files"
    STATUS_NO_CHANNELS = "status_no_channels"
    STATUS_IDLE = "status_idle"
    STATUS_WAITING = "status_waiting"
    STATUS_GENERATING_LIBRARY = "status_generating_library"
    STATUS_CANCELLING = "status_cancelling"
    STATUS_CANCELLED = "status_cancelled"
    STATUS_INPUT_LABEL = "status_input_label"
    STATUS_OUTPUT_LABEL = "status_output_label"
    STATUS_EMPTY_HINT = "status_empty_hint"
    PROGRESS_DIALOG = "progress_dialog"
    LOAD_DIALOG = "load_dialog"
    LOAD_FILE_PROMPT = "load_file_prompt"
    LOAD_DIRECTORY_PROMPT = "load_directory_prompt"
    CANCEL_DIALOG = "cancel_dialog"
    CANCEL_PROMPT = "cancel_prompt"
    PROGRESS_TEMPLATE = "progress_template"
    CONVERT_LABEL_TEMPLATE = "convert_label_template"
    STEMS_MODE = "stems_mode"
    STEMS_MODE_TOOLTIP = "stems_mode_tooltip"
    CHANNEL_CAP = "channel_cap"
    CHANNEL_CAP_TOOLTIP = "channel_cap_tooltip"
    HIERARCHY_MODE = "hierarchy_mode"
    HIERARCHY_MODE_TOOLTIP = "hierarchy_mode_tooltip"
    HIERARCHY_ROUND_ROBIN = "hierarchy_round_robin"
    HIERARCHY_STRICT = "hierarchy_strict"
    STEM_REMOVE = "stem_remove"
    STEMS_EMPTY_HINT = "stems_empty_hint"
    CONVERT_STEMS_BUTTON = "convert_stems_button"
    DISCARD_STEMS_DIALOG = "discard_stems_dialog"
    DISCARD_STEMS_PROMPT = "discard_stems_prompt"
    DISCARD_STEMS_BUTTON = "discard_stems_button"
    KEEP_STEMS_BUTTON = "keep_stems_button"
    STEM_SELECTION_DIALOG = "stem_selection_dialog"
    STEM_SELECTION_PROMPT = "stem_selection_prompt"
    STEM_SELECTION_LIMIT = "stem_selection_limit"
    ADD_STEMS_BUTTON = "add_stems_button"
    STATUS_STEM_REMOVE = "status_stem_remove"
    STATUS_STEMS_MODE = "status_stems_mode"
    STEM_LEVEL_CAPTION = "stem_level_caption"
    STEM_HANDLE = "stem_handle"
    STEM_HANDLE_TOOLTIP = "stem_handle_tooltip"
    STEM_INERT_TOOLTIP = "stem_inert_tooltip"


class ConverterStemMoveElements(AbstractElement):
    """The moves a gathered recording can make, as the row's menu names them."""

    CONTEXT_MOVE_UP = "context_move_up"
    CONTEXT_MOVE_DOWN = "context_move_down"
    CONTEXT_JOIN_ABOVE = "context_join_above"
    CONTEXT_JOIN_BELOW = "context_join_below"
    CONTEXT_ISOLATE = "context_isolate"
    CONTEXT_REMOVE_STEM = "context_remove_stem"


class AdvancedElements(AbstractElement):
    SECTION = "section"
    SECTION_METHOD = "section_method"
    SELECT_OUTPUT_DIRECTORY = "select_output_directory"
    SELECT_LIBRARY_DIRECTORY = "select_library_directory"
    COMBO_SPECTRUM_METHOD = "combo_spectrum_method"
    SLIDER_TRANSFORMATION_GAMMA = "slider_transformation_gamma"
    INPUT_MAX_WORKERS = "input_max_workers"
    TOOLTIP_SPECTRUM_METHOD = "tooltip_spectrum_method"
    TOOLTIP_TRANSFORMATION_GAMMA = "tooltip_transformation_gamma"
    TOOLTIP_MAX_WORKERS = "tooltip_max_workers"
    STATUS_SELECT_LIBRARY = "status_select_library"
    STATUS_SELECT_OUTPUT = "status_select_output"
