from sampletones_application.categories.abstract import AbstractElement


class ReconstructionsBrowserElements(AbstractElement):
    RECONSTRUCT_FILE_BUTTON = "reconstruct_file_button"
    RECONSTRUCT_DIRECTORY_BUTTON = "reconstruct_directory_button"
    REFRESH_BUTTON = "refresh_button"
    RECONSTRUCTIONS_TREE = "reconstructions_tree"
    CONTEXT_LOAD_RECONSTRUCTION = "context_load_reconstruction"
    FILE_NOT_FOUND = "file_not_found"
    AUDIO_FILE_NOT_FOUND = "audio_file_not_found"
    LOAD_ERROR = "load_error"
    INVALID_VALUES = "invalid_values"
    INVALID_FILE = "invalid_file"
    DESERIALIZATION_ERROR = "deserialization_error"
    LOAD_RECONSTRUCTION_DIALOG = "load_reconstruction_dialog"
    INCOMPATIBLE_VERSION_TEMPLATE = "incompatible_version_template"


class ReconstructionPanelElements(AbstractElement):
    AUDIO_SOURCE_LABEL = "audio_source_label"
    AUTOSCALE_CHECKBOX = "autoscale_checkbox"
    EXPORT_WAV_BUTTON = "export_wav_button"
    LOCATE_AUDIO_BUTTON = "locate_audio_button"
    ORIGINAL_AUDIO_RADIO = "original_audio_radio"
    RECONSTRUCTION_RADIO = "reconstruction_radio"
    WAVEFORM_LABEL = "waveform_label"
    AUTOSCALE_TOOLTIP = "autoscale_tooltip"
    LOCATE_AUDIO_FAILED = "locate_audio_failed"
    AUDIO_MISSING = "audio_missing"
    EXPORT_WAV_SUCCESS = "export_wav_success"
    EXPORT_WAV_FAILED = "export_wav_failed"
    AUDIO_MISSING_DIALOG = "audio_missing_dialog"


class ReconstructionsDetailsElements(AbstractElement):
    RECONSTRUCTION_DETAILS = "reconstruction_details"
    EXPORT_FTI_BUTTON = "export_fti_button"
    EXPORT_FTIS_BUTTON = "export_ftis_button"
    COPY_BUTTON = "copy_button"
    PITCH_LABEL = "pitch_label"
    HI_PITCH_LABEL = "hi_pitch_label"
    VOLUME_LABEL = "volume_label"
    ARPEGGIO_LABEL = "arpeggio_label"
    DUTY_CYCLE_LABEL = "duty_cycle_label"
    GENERATORS_TEXT = "generators_text"
    INITIAL_PERIOD = "initial_period"
    INITIAL_PITCH = "initial_pitch"
    STATUS_INPUT_PITCH = "status_input_pitch"
    STATUS_INPUT_PERIOD = "status_input_period"
    STATUS_BAR = "status_bar"
    STATUS_SEQUENCE = "status_sequence"
    STATUS_COPY_SEQUENCE = "status_copy_sequence"
    STATUS_GENERATOR_TOGGLE = "status_generator_toggle"
    STATUS_GENERATOR_NOT_AVAILABLE = "status_generator_not_available"
    EXPORT_FTI_SUCCESS = "export_fti_success"
    EXPORT_FTIS_SUCCESS = "export_ftis_success"
    EXPORT_FTI_FAILED = "export_fti_failed"
    EXPORT_FTIS_FAILED = "export_ftis_failed"
    EXPORT_STATUS_DIALOG = "export_status_dialog"
    NOT_LOADED_DIALOG = "not_loaded_dialog"
    EXPORT_WAV_DIALOG = "export_wav_dialog"
    EXPORT_FTI_DIALOG = "export_fti_dialog"
    LOAD_RECONSTRUCTION_DIALOG = "load_reconstruction_dialog"
    INITIAL_PITCH_TEMPLATE = "initial_pitch_template"
    INITIAL_PITCH_TOOLTIP_TEMPLATE = "initial_pitch_tooltip_template"
