from sampletones_application.categories.abstract import AbstractElement


class ReconstructionsBrowserElements(AbstractElement):
    REFRESH_BUTTON = "refresh_button"
    STATUS_REFRESH = "status_refresh"
    RECONSTRUCTIONS_TREE = "reconstructions_tree"
    CONTEXT_LOAD_RECONSTRUCTION = "context_load_reconstruction"
    CONTEXT_REMOVE_RECONSTRUCTION = "context_remove_reconstruction"
    CONTEXT_REMOVE_DIRECTORY = "context_remove_directory"
    FILE_NOT_FOUND = "file_not_found"
    AUDIO_FILE_NOT_FOUND = "audio_file_not_found"
    LOAD_ERROR = "load_error"
    INVALID_VALUES = "invalid_values"
    INVALID_FILE = "invalid_file"
    DESERIALIZATION_ERROR = "deserialization_error"
    LOAD_RECONSTRUCTION_DIALOG = "load_reconstruction_dialog"
    REMOVE_RECONSTRUCTION_DIALOG = "remove_reconstruction_dialog"
    REMOVE_RECONSTRUCTION_MESSAGE = "remove_reconstruction_message"
    REMOVE_DIRECTORY_DIALOG = "remove_directory_dialog"
    REMOVE_DIRECTORY_MESSAGE = "remove_directory_message"
    INCOMPATIBLE_VERSION_TEMPLATE = "incompatible_version_template"


class ReconstructionPanelElements(AbstractElement):
    AUDIO_SOURCE_LABEL = "audio_source_label"
    AUTOSCALE_CHECKBOX = "autoscale_checkbox"
    RECONSTRUCTION_FILE_LABEL = "reconstruction_file_label"
    PATH_NOT_FOUND = "path_not_found"
    PATH_NOT_APPLICABLE = "path_not_applicable"
    ORIGINAL_AUDIO_RADIO = "original_audio_radio"
    RECONSTRUCTION_RADIO = "reconstruction_radio"
    WAVEFORM_LABEL = "waveform_label"
    AUTOSCALE_TOOLTIP = "autoscale_tooltip"
    LOCATE_AUDIO_FAILED = "locate_audio_failed"
    EXPORT_WAV_SUCCESS = "export_wav_success"
    EXPORT_WAV_FAILED = "export_wav_failed"
    STEMS = "stems"
    STEMS_EMPTY = "stems_empty"
    STEMS_MODE_ROUND_ROBIN = "stems_mode_round_robin"
    STEMS_MODE_STRICT = "stems_mode_strict"
    STEMS_SETUP = "stems_setup"
    COLLAPSE_LEVELS = "collapse_levels"
    COLLAPSE_LEVELS_TOOLTIP = "collapse_levels_tooltip"
    STATUS_COLLAPSE_LEVELS = "status_collapse_levels"


class ReconstructionsInstrumentsElements(AbstractElement):
    SECTION = "section"
    EXPORT_INSTRUMENT_BUTTON = "export_instrument_button"
    COPY_BUTTON = "copy_button"
    PITCH_LABEL = "pitch_label"
    HI_PITCH_LABEL = "hi_pitch_label"
    VOLUME_LABEL = "volume_label"
    ARPEGGIO_LABEL = "arpeggio_label"
    DUTY_CYCLE_LABEL = "duty_cycle_label"
    INITIAL_PERIOD = "initial_period"
    INITIAL_PITCH = "initial_pitch"
    STATUS_INPUT_PITCH = "status_input_pitch"
    STATUS_INPUT_PERIOD = "status_input_period"
    STATUS_BAR = "status_bar"
    STATUS_SEQUENCE = "status_sequence"
    STATUS_SEQUENCE_TOO_LONG = "status_sequence_too_long"
    STATUS_COPY_SEQUENCE = "status_copy_sequence"
    STATUS_CHANNEL_TOGGLE = "status_channel_toggle"
    STATUS_CHANNEL_NOT_AVAILABLE = "status_channel_not_available"
    STATUS_EXPORT_INSTRUMENT = "status_export_instrument"
    EXPORT_INSTRUMENT_SUCCESS = "export_instrument_success"
    EXPORT_INSTRUMENTS_SUCCESS = "export_instruments_success"
    EXPORT_INSTRUMENT_TRUNCATED = "export_instrument_truncated"
    EXPORT_INSTRUMENTS_TRUNCATED = "export_instruments_truncated"
    EXPORT_INSTRUMENT_FAILED = "export_instrument_failed"
    EXPORT_INSTRUMENTS_FAILED = "export_instruments_failed"
    EXPORT_STATUS_DIALOG = "export_status_dialog"
    NOT_LOADED_DIALOG = "not_loaded_dialog"
    EXPORT_WAV_DIALOG = "export_wav_dialog"
    EXPORT_INSTRUMENT_DIALOG = "export_instrument_dialog"
    EXPORT_INSTRUMENTS_DIALOG = "export_instruments_dialog"
    INITIAL_PITCH_TOOLTIP_TEMPLATE = "initial_pitch_tooltip_template"
