from sampletones_application.categories.abstract import AbstractElement


class SequencerTrackerElements(AbstractElement):
    TRACKER_TEXT = "tracker_text"
    OCTAVE = "octave"
    COLUMN_ROW = "column_row"
    COLUMN_VOICE = "column_voice"
    COLUMN_PULSE_1 = "column_pulse_1"
    COLUMN_PULSE_2 = "column_pulse_2"
    COLUMN_TRIANGLE = "column_triangle"
    COLUMN_NOISE = "column_noise"
    HEADER_CHANNEL = "header_channel"
    HEADER_VOICE = "header_voice"
    CONTEXT_PLAY = "context_play"
    CONTEXT_PLAY_FROM_FRAME = "context_play_from_frame"
    CONTEXT_SELECT_ALL = "context_select_all"
    CONTEXT_SELECT_COLUMN = "context_select_column"
    CONTEXT_SELECT_SUBCOLUMN = "context_select_subcolumn"
    CONTEXT_NOTE_OFF = "context_note_off"
    CONTEXT_SET_VOICE = "context_set_voice"
    CONTEXT_NO_VOICES = "context_no_voices"
    CONTEXT_CLEAR_SUBCOLUMN = "context_clear_subcolumn"
    CONTEXT_CLEAR_CELL = "context_clear_cell"
    CONTEXT_CLEAR_ROW = "context_clear_row"
    CONTEXT_TRANSPOSE_UP = "context_transpose_up"
    CONTEXT_TRANSPOSE_DOWN = "context_transpose_down"
    CONTEXT_TRANSPOSE_OCTAVE_UP = "context_transpose_octave_up"
    CONTEXT_TRANSPOSE_OCTAVE_DOWN = "context_transpose_octave_down"
    CONTEXT_VOLUME_UP = "context_volume_up"
    CONTEXT_VOLUME_DOWN = "context_volume_down"
    CONTEXT_VOLUME_UP_COARSE = "context_volume_up_coarse"
    CONTEXT_VOLUME_DOWN_COARSE = "context_volume_down_coarse"
    CONTEXT_MUTE = "context_mute"
    CONTEXT_UNMUTE = "context_unmute"
    CONTEXT_SOLO = "context_solo"
    CONTEXT_UNSOLO = "context_unsolo"
    CONTEXT_MUTE_ALL = "context_mute_all"
    CONTEXT_UNMUTE_ALL = "context_unmute_all"


class SequencerOrderElements(AbstractElement):
    ORDER_TEXT = "order_text"
    ROW_MASTER = "row_master"
    ROW_PULSE_1 = "row_pulse_1"
    ROW_PULSE_2 = "row_pulse_2"
    ROW_TRIANGLE = "row_triangle"
    ROW_NOISE = "row_noise"
    LABEL_CHANNEL = "label_channel"
    LABEL_MASTER = "label_master"
    CONTEXT_PLAY = "context_play"
    CONTEXT_SELECT_ALL = "context_select_all"
    CONTEXT_SELECT_ROW = "context_select_row"
    CONTEXT_DUPLICATE = "context_duplicate"
    CONTEXT_CLONE = "context_clone"
    CONTEXT_INSERT = "context_insert"
    CONTEXT_CLEAR = "context_clear"
    CONTEXT_REMOVE = "context_remove"
    CONTEXT_MOVE_LEFT = "context_move_left"
    CONTEXT_MOVE_RIGHT = "context_move_right"
    CONTEXT_MOVE_START = "context_move_start"
    CONTEXT_MOVE_END = "context_move_end"
    CONTEXT_MUTE = "context_mute"
    CONTEXT_UNMUTE = "context_unmute"
    CONTEXT_SOLO = "context_solo"
    CONTEXT_UNSOLO = "context_unsolo"
    CONTEXT_MUTE_ALL = "context_mute_all"
    CONTEXT_UNMUTE_ALL = "context_unmute_all"


class SequencerVoicesElements(AbstractElement):
    VOICES_TEXT = "voices_text"
    NEW_INSTRUMENT = "new_instrument"
    ADD_SAMPLE = "add_sample"
    IMPORT_INSTRUMENT = "import_instrument"
    KIND_SAMPLE = "kind_sample"
    KIND_INSTRUMENT = "kind_instrument"
    COLUMN_KIND = "column_kind"
    COLUMN_ID = "column_id"
    COLUMN_NAME = "column_name"
    COLUMN_LOOP = "column_loop"
    CONTEXT_EDIT = "context_edit"
    CONTEXT_RENAME = "context_rename"
    CONTEXT_DUPLICATE = "context_duplicate"
    CONTEXT_REMOVE = "context_remove"
    CONTEXT_MOVE_UP = "context_move_up"
    CONTEXT_MOVE_DOWN = "context_move_down"
    CONTEXT_MOVE_TOP = "context_move_top"
    CONTEXT_MOVE_BOTTOM = "context_move_bottom"
    OMISSION_PITCH = "omission_pitch"
    OMISSION_HI_PITCH = "omission_hi_pitch"
    OMISSION_RELEASE_POINT = "omission_release_point"
    OMISSION_ARPEGGIO_MODE = "omission_arpeggio_mode"
    OMISSION_SEQUENCE_LOOP_POINTS = "omission_sequence_loop_points"


class SequencerHistoryElements(AbstractElement):
    HISTORY_TEXT = "history_text"
    UNDO = "undo"
    REDO = "redo"
    STATUS_UNDO = "status_undo"
    STATUS_REDO = "status_redo"
    EMPTY = "empty"
    LOOP_ON = "loop_on"
    LOOP_OFF = "loop_off"
