from sampletones_application.categories.abstract import AbstractElement


class AudioSettingsElements(AbstractElement):
    OUTPUT_DEVICE = "output_device"
    DEVICE_LABEL = "device_label"
    SAMPLE_RATE = "sample_rate"
    SAMPLE_RATE_LABEL = "sample_rate_label"
    BUFFER_SIZE = "buffer_size"
    MASTER_GAIN = "master_gain"
    MASTER_GAIN_DB = "master_gain_db"
    MASTER_GAIN_SILENT = "master_gain_silent"
    APPLY_BUTTON = "apply_button"
    REFRESH_DEVICES_BUTTON = "refresh_devices_button"
    WINDOW_TITLE = "window_title"


class ProjectPropertiesElements(AbstractElement):
    WINDOW_TITLE = "window_title"
    TITLE = "title"
    AUTHOR = "author"
    COMMENT = "comment"
    FIRST_HIGHLIGHT = "first_highlight"
    SECOND_HIGHLIGHT = "second_highlight"
    CREATED = "created"
    MODIFIED = "modified"


class KeybindingActionElements(AbstractElement):
    """The name a reader finds each editable action under, one member per :class:`ShortcutId`.

    A member is named after the action it labels, so an action reaches its text through
    ``KeybindingActionElements[shortcut_id.name]`` and a new action ships only once a reader has a
    name for it.
    """

    NEW_PROJECT = "new_project"
    OPEN_PROJECT = "open_project"
    SAVE_PROJECT = "save_project"
    SAVE_PROJECT_AS = "save_project_as"
    PROJECT_PROPERTIES = "project_properties"
    EXPORT_PROJECT_FAMITRACKER = "export_project_famitracker"
    EXPORT_PROJECT_BITPHASE = "export_project_bitphase"
    RENDER_SONG = "render_song"
    CLOSE_PROJECT = "close_project"
    EXIT = "exit"
    UNDO = "undo"
    REDO = "redo"
    RECONSTRUCT_FILE = "reconstruct_file"
    RECONSTRUCT_DIRECTORY = "reconstruct_directory"
    LOAD_GENERATION_SETTINGS = "load_generation_settings"
    SAVE_GENERATION_SETTINGS = "save_generation_settings"
    OPEN_RECONSTRUCTION = "open_reconstruction"
    SAVE_RECONSTRUCTION = "save_reconstruction"
    SAVE_RECONSTRUCTION_AS = "save_reconstruction_as"
    CLOSE_RECONSTRUCTION = "close_reconstruction"
    EXPORT_RECONSTRUCTION_WAV = "export_reconstruction_wav"
    EXPORT_INSTRUMENTS_FAMITRACKER = "export_instruments_famitracker"
    EXPORT_INSTRUMENTS_BITPHASE_PRESET = "export_instruments_bitphase_preset"
    ADD_RECONSTRUCTION_TO_SEQUENCER = "add_reconstruction_to_sequencer"
    OPEN_RECONSTRUCTION_IN_EXPLORER = "open_reconstruction_in_explorer"
    LOCATE_ORIGINAL_AUDIO = "locate_original_audio"
    PLAY = "play"
    PLAY_FROM_START = "play_from_start"
    PLAY_FROM_FRAME = "play_from_frame"
    STOP = "stop"
    TOGGLE_AUTOPLAY = "toggle_autoplay"
    FOLLOW_ROWS = "follow_rows"
    FOLLOW_PATTERNS = "follow_patterns"
    FOLLOW_OFF = "follow_off"
    TOGGLE_LOOP_SONG = "toggle_loop_song"
    TOGGLE_CHANNEL_PULSE_1 = "toggle_channel_pulse_1"
    TOGGLE_CHANNEL_PULSE_2 = "toggle_channel_pulse_2"
    TOGGLE_CHANNEL_TRIANGLE = "toggle_channel_triangle"
    TOGGLE_CHANNEL_NOISE = "toggle_channel_noise"
    UNMUTE_ALL_CHANNELS = "unmute_all_channels"
    AUDIO_SETTINGS = "audio_settings"
    DISPLAY_SETTINGS = "display_settings"
    KEYBOARD_SETTINGS = "keyboard_settings"
    TOGGLE_ADVANCED_SETTINGS = "toggle_advanced_settings"
    TOGGLE_FULLSCREEN = "toggle_fullscreen"
    ABOUT_DIALOG = "about_dialog"
    NEXT_TAB = "next_tab"
    PREVIOUS_TAB = "previous_tab"

    ORDER_PREVIOUS_POSITION = "order_previous_position"
    ORDER_NEXT_POSITION = "order_next_position"
    ORDER_PREVIOUS_CHANNEL = "order_previous_channel"
    ORDER_NEXT_CHANNEL = "order_next_channel"
    ORDER_FIRST_POSITION = "order_first_position"
    ORDER_LAST_POSITION = "order_last_position"
    ORDER_EXTEND_SELECTION_UP = "order_extend_selection_up"
    ORDER_EXTEND_SELECTION_DOWN = "order_extend_selection_down"
    ORDER_EXTEND_SELECTION_LEFT = "order_extend_selection_left"
    ORDER_EXTEND_SELECTION_RIGHT = "order_extend_selection_right"
    ORDER_EXTEND_SELECTION_TO_FIRST_POSITION = "order_extend_selection_to_first_position"
    ORDER_EXTEND_SELECTION_TO_LAST_POSITION = "order_extend_selection_to_last_position"
    ORDER_MOVE_FRAME_LEFT = "order_move_frame_left"
    ORDER_MOVE_FRAME_RIGHT = "order_move_frame_right"
    ORDER_MOVE_FRAME_TO_START = "order_move_frame_to_start"
    ORDER_MOVE_FRAME_TO_END = "order_move_frame_to_end"
    ORDER_ADD_FRAME = "order_add_frame"
    ORDER_INSERT_FRAME = "order_insert_frame"
    ORDER_REMOVE_FRAME = "order_remove_frame"
    ORDER_DUPLICATE_FRAME = "order_duplicate_frame"
    ORDER_CLONE_FRAME = "order_clone_frame"
    ORDER_CLEAR_FRAME = "order_clear_frame"
    ORDER_CLEAR_CELL = "order_clear_cell"
    ORDER_CLEAR_PREVIOUS_CELL = "order_clear_previous_cell"
    ORDER_CANCEL_ENTRY = "order_cancel_entry"

    TRACKER_PREVIOUS_ROW = "tracker_previous_row"
    TRACKER_NEXT_ROW = "tracker_next_row"
    TRACKER_PREVIOUS_SUBCOLUMN = "tracker_previous_subcolumn"
    TRACKER_NEXT_SUBCOLUMN = "tracker_next_subcolumn"
    TRACKER_PREVIOUS_COLUMN = "tracker_previous_column"
    TRACKER_NEXT_COLUMN = "tracker_next_column"
    TRACKER_FIRST_ROW = "tracker_first_row"
    TRACKER_LAST_ROW = "tracker_last_row"
    TRACKER_EXTEND_SELECTION_UP = "tracker_extend_selection_up"
    TRACKER_EXTEND_SELECTION_DOWN = "tracker_extend_selection_down"
    TRACKER_EXTEND_SELECTION_LEFT = "tracker_extend_selection_left"
    TRACKER_EXTEND_SELECTION_RIGHT = "tracker_extend_selection_right"
    TRACKER_EXTEND_SELECTION_TO_FIRST_ROW = "tracker_extend_selection_to_first_row"
    TRACKER_EXTEND_SELECTION_TO_LAST_ROW = "tracker_extend_selection_to_last_row"
    TRACKER_COPY_BLOCK = "tracker_copy_block"
    TRACKER_CUT_BLOCK = "tracker_cut_block"
    TRACKER_PASTE_BLOCK = "tracker_paste_block"
    TRACKER_PAGE_UP = "tracker_page_up"
    TRACKER_PAGE_DOWN = "tracker_page_down"
    TRACKER_CLEAR_ROW = "tracker_clear_row"
    TRACKER_CLEAR_PREVIOUS_ROW = "tracker_clear_previous_row"
    TRACKER_CANCEL_ENTRY = "tracker_cancel_entry"
    TRACKER_PLAY_FROM_ROW = "tracker_play_from_row"

    SAMPLES_RENAME_SAMPLE = "samples_rename_sample"
    SAMPLES_REMOVE_SAMPLE = "samples_remove_sample"
    SAMPLES_MOVE_SAMPLE_UP = "samples_move_sample_up"
    SAMPLES_MOVE_SAMPLE_DOWN = "samples_move_sample_down"
    SAMPLES_MOVE_SAMPLE_TO_TOP = "samples_move_sample_to_top"
    SAMPLES_MOVE_SAMPLE_TO_BOTTOM = "samples_move_sample_to_bottom"
    SAMPLES_CANCEL_RENAME = "samples_cancel_rename"


class KeybindingCategoryElements(AbstractElement):
    """The name a reader finds each editable scope under, one member per :class:`ShortcutCategory`."""

    APPLICATION = "application"
    ORDER = "order"
    TRACKER = "tracker"
    SAMPLES = "samples"


class KeybindingsElements(AbstractElement):
    """The keybindings dialog's own text, apart from the actions it lists."""

    WINDOW_TITLE = "window_title"
    SCHEME = "scheme"
    FILTER = "filter"
    ACTION = "action"
    SHORTCUT = "shortcut"
    UNBOUND = "unbound"
    CAPTURING = "capturing"
    CLEAR_BUTTON = "clear_button"
    RESET_BUTTON = "reset_button"
    REASSIGN_BUTTON = "reassign_button"
    DISCARD_BUTTON = "discard_button"
    KEEP_EDITING_BUTTON = "keep_editing_button"
    REASSIGN_CONFIRMATION = "reassign_confirmation"
    RESET_CONFIRMATION = "reset_confirmation"
    DISCARD_CONFIRMATION = "discard_confirmation"
    UNREADABLE_COMBINATION = "unreadable_combination"
