from sampletones_application.constants.global_ import TAG_SEPARATOR

SUF_PLAYER_PLAY = f"{TAG_SEPARATOR}play"
SUF_PLAYER_PAUSE = f"{TAG_SEPARATOR}pause"
SUF_PLAYER_STOP = f"{TAG_SEPARATOR}stop"
SUF_PLAYER_POSITION = f"{TAG_SEPARATOR}position"
SUF_PLAYER_CARD = f"{TAG_SEPARATOR}card"
SUF_PLAYER_TOOLTIP = f"{TAG_SEPARATOR}tooltip"
