from sampletones_application.categories.hierarchy import Page, Panel, Widget
from sampletones_application.categories.key.tag import TagName
from sampletones_application.tags.compose import compose_tag

TAG_RECONSTRUCTIONS_RECONSTRUCTION_DIALOG_NOT_LOADED = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.DIALOG,
    "not_loaded",
)
TAG_RECONSTRUCTIONS_BROWSER_PANEL = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.PANEL,
    "browser",
)
TAG_RECONSTRUCTIONS_BROWSER_TREE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.TREE,
    "browser",
)
TAG_RECONSTRUCTIONS_BROWSER_GROUP_TREE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.GROUP,
    "tree",
)
TAG_RECONSTRUCTIONS_BROWSER_WINDOW_TREE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.WINDOW,
    "tree",
)
TAG_RECONSTRUCTIONS_BROWSER_GROUP_CONTROLS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.GROUP,
    "controls",
)
TAG_RECONSTRUCTIONS_BROWSER_BUTTON_REFRESH_RECONSTRUCTIONS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.BUTTON,
    "refresh_reconstructions",
)
TAG_RECONSTRUCTIONS_BROWSER_DIALOG_REMOVE_RECONSTRUCTION_CONFIRMATION = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.DIALOG,
    "remove_reconstruction_confirmation",
)
TAG_RECONSTRUCTIONS_BROWSER_DIALOG_REMOVE_DIRECTORY_CONFIRMATION = TagName(
    Page.RECONSTRUCTIONS,
    Panel.BROWSER,
    Widget.DIALOG,
    "remove_directory_confirmation",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PANEL_RECONSTRUCTION_WAVEFORM = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "reconstruction_waveform",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PANEL_AUDIO = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "audio",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PANEL_PLOT = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "plot",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_GROUP_CHANNELS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.GROUP,
    "channels",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_GROUP_AUDIO_SOURCE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.GROUP,
    "audio_source",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_RADIO_AUDIO_SOURCE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.RADIO,
    "audio_source",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PATH_RECONSTRUCTION_FILE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PATH,
    "reconstruction_file",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_PANEL_STEMS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.PANEL,
    "stems",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_TEXT_STEMS_SETUP = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.TEXT,
    "stems_setup",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_TEXT_STEMS_EMPTY = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.TEXT,
    "stems_empty",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_CHECKBOX_COLLAPSE_LEVELS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.CHECKBOX,
    "collapse_levels",
)
TAG_RECONSTRUCTIONS_RECONSTRUCTION_TOOLTIP_COLLAPSE_LEVELS = TagName(
    Page.RECONSTRUCTIONS,
    Panel.RECONSTRUCTION,
    Widget.TOOLTIP,
    "collapse_levels",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_PANEL = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.PANEL,
    "instruments",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_TABS_BAR = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.TABS,
    "bar",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_BUTTON_EXPORT_INSTRUMENT = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.BUTTON,
    "export_instrument",
)
TAG_RECONSTRUCTIONS_INSTRUMENTS_TEXT_SAMPLE_SIZE = TagName(
    Page.RECONSTRUCTIONS,
    Panel.INSTRUMENTS,
    Widget.TEXT,
    "sample_size",
)

PRE_RECONSTRUCTION_CHANNEL = compose_tag("reconstruction", "channel")
PRE_RECONSTRUCTION_STEMS = compose_tag("reconstruction", "stems")
SUF_RECONSTRUCTIONS_INSTRUMENTS_NO_DATA_MESSAGE = "no_data_message"
SUF_RECONSTRUCTIONS_INSTRUMENTS_INSTRUMENT_SIZE = "instrument_size"
SUF_RECONSTRUCTIONS_INSTRUMENTS_WINDOW = "window"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_AUTOSCALE = "autoscale"
