# automatically generated by the FlatBuffers compiler, do not modify

# namespace: reconstruction

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBErrors(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBErrors()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBErrors(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBErrors
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBErrors
    def GeneratorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBErrors
    def Errors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # FBErrors
    def ErrorsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FBErrors
    def ErrorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBErrors
    def ErrorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FBErrors
    def TotalError(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0


def FBErrorsStart(builder):
    builder.StartObject(3)


def Start(builder):
    return FBErrorsStart(builder)


def FBErrorsAddGeneratorName(builder, generatorName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(generatorName), 0)


def AddGeneratorName(builder, generatorName):
    return FBErrorsAddGeneratorName(builder, generatorName)


def FBErrorsAddErrors(builder, errors):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(errors), 0)


def AddErrors(builder, errors):
    return FBErrorsAddErrors(builder, errors)


def FBErrorsStartErrorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartErrorsVector(builder, numElems):
    return FBErrorsStartErrorsVector(builder, numElems)


def FBErrorsAddTotalError(builder, totalError):
    builder.PrependFloat32Slot(2, totalError, 0.0)


def AddTotalError(builder, totalError):
    return FBErrorsAddTotalError(builder, totalError)


def FBErrorsEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBErrorsEnd(builder)
