# automatically generated by the FlatBuffers compiler, do not modify

# namespace: reconstruction

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBInstructionsItem(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBInstructionsItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBInstructionsItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBInstructionsItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBInstructionsItem
    def GeneratorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBInstructionsItem
    def Instructions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from schemas.instructions.FBInstructionData import FBInstructionData

            obj = FBInstructionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBInstructionsItem
    def InstructionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBInstructionsItem
    def InstructionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def FBInstructionsItemStart(builder):
    builder.StartObject(2)


def Start(builder):
    return FBInstructionsItemStart(builder)


def FBInstructionsItemAddGeneratorName(builder, generatorName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(generatorName), 0)


def AddGeneratorName(builder, generatorName):
    return FBInstructionsItemAddGeneratorName(builder, generatorName)


def FBInstructionsItemAddInstructions(builder, instructions):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(instructions), 0)


def AddInstructions(builder, instructions):
    return FBInstructionsItemAddInstructions(builder, instructions)


def FBInstructionsItemStartInstructionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartInstructionsVector(builder, numElems):
    return FBInstructionsItemStartInstructionsVector(builder, numElems)


def FBInstructionsItemEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBInstructionsItemEnd(builder)
