# automatically generated by the FlatBuffers compiler, do not modify

# namespace: reconstruction

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBReconstruction(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBReconstruction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBReconstruction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBReconstruction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBReconstruction
    def Metadata(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.metadata.FBMetadata import FBMetadata

            obj = FBMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBReconstruction
    def AudioFilepath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBReconstruction
    def Config(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.configs.FBConfig import FBConfig

            obj = FBConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBReconstruction
    def Approximation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # FBReconstruction
    def ApproximationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FBReconstruction
    def ApproximationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBReconstruction
    def ApproximationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FBReconstruction
    def ApproximationsData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from schemas.reconstruction.FBApproximationsItem import FBApproximationsItem

            obj = FBApproximationsItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBReconstruction
    def ApproximationsDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBReconstruction
    def ApproximationsDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # FBReconstruction
    def InstructionsData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from schemas.reconstruction.FBInstructionsItem import FBInstructionsItem

            obj = FBInstructionsItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBReconstruction
    def InstructionsDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBReconstruction
    def InstructionsDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # FBReconstruction
    def ErrorsData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from schemas.reconstruction.FBErrors import FBErrors

            obj = FBErrors()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBReconstruction
    def ErrorsDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBReconstruction
    def ErrorsDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # FBReconstruction
    def Coefficient(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0


def FBReconstructionStart(builder):
    builder.StartObject(8)


def Start(builder):
    return FBReconstructionStart(builder)


def FBReconstructionAddMetadata(builder, metadata):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)


def AddMetadata(builder, metadata):
    return FBReconstructionAddMetadata(builder, metadata)


def FBReconstructionAddAudioFilepath(builder, audioFilepath):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(audioFilepath), 0)


def AddAudioFilepath(builder, audioFilepath):
    return FBReconstructionAddAudioFilepath(builder, audioFilepath)


def FBReconstructionAddConfig(builder, config):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(config), 0)


def AddConfig(builder, config):
    return FBReconstructionAddConfig(builder, config)


def FBReconstructionAddApproximation(builder, approximation):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(approximation), 0)


def AddApproximation(builder, approximation):
    return FBReconstructionAddApproximation(builder, approximation)


def FBReconstructionStartApproximationVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartApproximationVector(builder, numElems):
    return FBReconstructionStartApproximationVector(builder, numElems)


def FBReconstructionAddApproximationsData(builder, approximationsData):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(approximationsData), 0)


def AddApproximationsData(builder, approximationsData):
    return FBReconstructionAddApproximationsData(builder, approximationsData)


def FBReconstructionStartApproximationsDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartApproximationsDataVector(builder, numElems):
    return FBReconstructionStartApproximationsDataVector(builder, numElems)


def FBReconstructionAddInstructionsData(builder, instructionsData):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(instructionsData), 0)


def AddInstructionsData(builder, instructionsData):
    return FBReconstructionAddInstructionsData(builder, instructionsData)


def FBReconstructionStartInstructionsDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartInstructionsDataVector(builder, numElems):
    return FBReconstructionStartInstructionsDataVector(builder, numElems)


def FBReconstructionAddErrorsData(builder, errorsData):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(errorsData), 0)


def AddErrorsData(builder, errorsData):
    return FBReconstructionAddErrorsData(builder, errorsData)


def FBReconstructionStartErrorsDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartErrorsDataVector(builder, numElems):
    return FBReconstructionStartErrorsDataVector(builder, numElems)


def FBReconstructionAddCoefficient(builder, coefficient):
    builder.PrependFloat32Slot(7, coefficient, 0.0)


def AddCoefficient(builder, coefficient):
    return FBReconstructionAddCoefficient(builder, coefficient)


def FBReconstructionEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBReconstructionEnd(builder)
