# automatically generated by the FlatBuffers compiler, do not modify

# namespace: reconstruction

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBApproximationsItem(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBApproximationsItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBApproximationsItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBApproximationsItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBApproximationsItem
    def GeneratorName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBApproximationsItem
    def Approximation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # FBApproximationsItem
    def ApproximationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FBApproximationsItem
    def ApproximationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBApproximationsItem
    def ApproximationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0


def FBApproximationsItemStart(builder):
    builder.StartObject(2)


def Start(builder):
    return FBApproximationsItemStart(builder)


def FBApproximationsItemAddGeneratorName(builder, generatorName):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(generatorName), 0)


def AddGeneratorName(builder, generatorName):
    return FBApproximationsItemAddGeneratorName(builder, generatorName)


def FBApproximationsItemAddApproximation(builder, approximation):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(approximation), 0)


def AddApproximation(builder, approximation):
    return FBApproximationsItemAddApproximation(builder, approximation)


def FBApproximationsItemStartApproximationVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartApproximationVector(builder, numElems):
    return FBApproximationsItemStartApproximationVector(builder, numElems)


def FBApproximationsItemEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBApproximationsItemEnd(builder)
