import threading
from typing import Any, Dict, Optional, Tuple, Type, TypeVar

T = TypeVar("T")

class SingletonMeta(type):
    _instances: Dict[Type[Any], Any]
    _instance_lock: threading.Lock
    _lock: threading.Lock
    def __init__(cls, name: str, bases: Tuple[Type[Any], ...], namespace: Dict[str, Any]) -> None: ...
    def __call__(self: Type[T], *args: Any, **kwargs: Any) -> T: ...
    def get_instance(self: Type[T]) -> Optional[T]: ...
    def has_instance(self) -> bool: ...
    def clear_instances(self) -> None: ...
    def clear_instance(self, target_cls: Type[Any]) -> None: ...
