scheduling:
  delays:
    schedule: 12
    reconstruction_update: 1
    cancel: 30
  priorities:
    update_status: 0
    gui_action: 2
    schedule: 1
  emit:
    priority: 100
    batch_size: 128
  queue_budget_seconds: 0.005

ui:
  status_bar_display_time: 2.0
  fps_update_interval: 2.0

display:
  resolutions:
    - width: 1024
      height: 768
    - width: 1152
      height: 648
    - width: 1280
      height: 720
    - width: 1280
      height: 800
    - width: 1366
      height: 768
    - width: 1440
      height: 900
    - width: 1600
      height: 900
    - width: 1680
      height: 1050
    - width: 1920
      height: 1080
    - width: 1920
      height: 1200
    - width: 2560
      height: 1080
    - width: 2560
      height: 1440
    - width: 2560
      height: 1600
    - width: 3440
      height: 1440
    - width: 3840
      height: 2160
  frame_rates:
    - 0
    - 30
    - 60
    - 75
    - 90
    - 120
    - 144
    - 165
    - 240
  revert_countdown_seconds: 10.0
