# automatically generated by the FlatBuffers compiler, do not modify

# namespace: instructions


class FBInstructionUnion(object):
    NONE = 0
    sampletones_schemas_instructions_FBPulseInstruction = 1
    sampletones_schemas_instructions_FBTriangleInstruction = 2
    sampletones_schemas_instructions_FBNoiseInstruction = 3
