# automatically generated by the FlatBuffers compiler, do not modify

# namespace: instructions

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBPulseInstruction(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBPulseInstruction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBPulseInstruction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBPulseInstruction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBPulseInstruction
    def On(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBPulseInstruction
    def Pitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBPulseInstruction
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBPulseInstruction
    def DutyCycle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0


def FBPulseInstructionStart(builder):
    builder.StartObject(4)


def Start(builder):
    return FBPulseInstructionStart(builder)


def FBPulseInstructionAddOn(builder, on):
    builder.PrependBoolSlot(0, on, 0)


def AddOn(builder, on):
    return FBPulseInstructionAddOn(builder, on)


def FBPulseInstructionAddPitch(builder, pitch):
    builder.PrependInt32Slot(1, pitch, 0)


def AddPitch(builder, pitch):
    return FBPulseInstructionAddPitch(builder, pitch)


def FBPulseInstructionAddVolume(builder, volume):
    builder.PrependInt32Slot(2, volume, 0)


def AddVolume(builder, volume):
    return FBPulseInstructionAddVolume(builder, volume)


def FBPulseInstructionAddDutyCycle(builder, dutyCycle):
    builder.PrependInt32Slot(3, dutyCycle, 0)


def AddDutyCycle(builder, dutyCycle):
    return FBPulseInstructionAddDutyCycle(builder, dutyCycle)


def FBPulseInstructionEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBPulseInstructionEnd(builder)
