from typing import Any, Callable, Iterator, Optional, Tuple

class NodeMixin:
    separator: str

    @property
    def parent(self) -> Any: ...
    @parent.setter
    def parent(self, value: Any) -> None: ...
    @property
    def children(self) -> Tuple[Any, ...]: ...
    @children.setter
    def children(self, value: Any) -> None: ...
    @property
    def path(self) -> Tuple[Any, ...]: ...
    @property
    def root(self) -> Any: ...
    @property
    def ancestors(self) -> Tuple[Any, ...]: ...
    @property
    def descendants(self) -> Tuple[Any, ...]: ...
    @property
    def siblings(self) -> Tuple[Any, ...]: ...
    @property
    def leaves(self) -> Tuple[Any, ...]: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def height(self) -> int: ...
    @property
    def depth(self) -> int: ...
    def iter_path_reverse(self) -> Iterator[Any]: ...

class Node(NodeMixin):
    name: Any

    def __init__(
        self,
        name: Any,
        parent: Optional[Any] = ...,
        children: Optional[Any] = ...,
        **kwargs: Any,
    ) -> None: ...

class PreOrderIter:
    def __init__(
        self,
        node: NodeMixin,
        filter_: Optional[Callable[[Any], bool]] = ...,
        stop: Optional[Callable[[Any], bool]] = ...,
        maxlevel: Optional[int] = ...,
    ) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
