# automatically generated by the FlatBuffers compiler, do not modify

# namespace: configs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBCalculationConfig(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBCalculationConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBCalculationConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBCalculationConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBCalculationConfig
    def FindBestPhase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBCalculationConfig
    def FastDifference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False


def FBCalculationConfigStart(builder):
    builder.StartObject(2)


def Start(builder):
    return FBCalculationConfigStart(builder)


def FBCalculationConfigAddFindBestPhase(builder, findBestPhase):
    builder.PrependBoolSlot(0, findBestPhase, 0)


def AddFindBestPhase(builder, findBestPhase):
    return FBCalculationConfigAddFindBestPhase(builder, findBestPhase)


def FBCalculationConfigAddFastDifference(builder, fastDifference):
    builder.PrependBoolSlot(1, fastDifference, 0)


def AddFastDifference(builder, fastDifference):
    return FBCalculationConfigAddFastDifference(builder, fastDifference)


def FBCalculationConfigEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBCalculationConfigEnd(builder)
