# automatically generated by the FlatBuffers compiler, do not modify

# namespace: configs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBWeightsConfig(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBWeightsConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBWeightsConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBWeightsConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBWeightsConfig
    def SpectralLossWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FBWeightsConfig
    def TemporalLossWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0


def FBWeightsConfigStart(builder):
    builder.StartObject(2)


def Start(builder):
    return FBWeightsConfigStart(builder)


def FBWeightsConfigAddSpectralLossWeight(builder, spectralLossWeight):
    builder.PrependFloat32Slot(0, spectralLossWeight, 0.0)


def AddSpectralLossWeight(builder, spectralLossWeight):
    return FBWeightsConfigAddSpectralLossWeight(builder, spectralLossWeight)


def FBWeightsConfigAddTemporalLossWeight(builder, temporalLossWeight):
    builder.PrependFloat32Slot(1, temporalLossWeight, 0.0)


def AddTemporalLossWeight(builder, temporalLossWeight):
    return FBWeightsConfigAddTemporalLossWeight(builder, temporalLossWeight)


def FBWeightsConfigEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBWeightsConfigEnd(builder)
