# automatically generated by the FlatBuffers compiler, do not modify

# namespace: noise

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBNoiseInstruction(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBNoiseInstruction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBNoiseInstruction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBNoiseInstruction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBNoiseInstruction
    def On(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBNoiseInstruction
    def Period(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBNoiseInstruction
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBNoiseInstruction
    def Short(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False


def FBNoiseInstructionStart(builder):
    builder.StartObject(4)


def Start(builder):
    return FBNoiseInstructionStart(builder)


def FBNoiseInstructionAddOn(builder, on):
    builder.PrependBoolSlot(0, on, 0)


def AddOn(builder, on):
    return FBNoiseInstructionAddOn(builder, on)


def FBNoiseInstructionAddPeriod(builder, period):
    builder.PrependInt32Slot(1, period, 0)


def AddPeriod(builder, period):
    return FBNoiseInstructionAddPeriod(builder, period)


def FBNoiseInstructionAddVolume(builder, volume):
    builder.PrependInt32Slot(2, volume, 0)


def AddVolume(builder, volume):
    return FBNoiseInstructionAddVolume(builder, volume)


def FBNoiseInstructionAddShort(builder, short):
    builder.PrependBoolSlot(3, short, 0)


def AddShort(builder, short):
    return FBNoiseInstructionAddShort(builder, short)


def FBNoiseInstructionEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBNoiseInstructionEnd(builder)
