from typing import Protocol


class AudioPlayerProtocol(Protocol):
    def play(self) -> None: ...

    def pause_or_resume(self) -> None: ...

    def stop(self) -> None: ...

    def is_playing(self) -> bool: ...

    def is_paused(self) -> bool: ...

    def is_engaged(self) -> bool: ...

    def is_loaded(self) -> bool: ...


class SamplePlayerProtocol(AudioPlayerProtocol, Protocol):
    """A transport player sounding one stretch of audio, which a reader can point at a sample of."""

    def play_from(self, position: int) -> None: ...
