from typing import Protocol


class AudioPlayerProtocol(Protocol):
    def play(self) -> None: ...

    def pause_or_resume(self) -> None: ...

    def stop(self) -> None: ...

    def is_playing(self) -> bool: ...

    def is_paused(self) -> bool: ...

    def is_engaged(self) -> bool: ...

    def is_loaded(self) -> bool: ...
