from enum import Enum


class ShortcutId(Enum):
    NEW_PROJECT = "NewProject"
    OPEN_PROJECT = "OpenProject"
    SAVE_PROJECT = "SaveProject"
    SAVE_PROJECT_AS = "SaveProjectAs"
    PROJECT_PROPERTIES = "ProjectProperties"
    EXPORT_PROJECT_MODULE = "ExportProjectModule"
    CLOSE_PROJECT = "CloseProject"
    EXIT = "Exit"
    UNDO = "Undo"
    REDO = "Redo"
    RECONSTRUCT_FILE = "ReconstructFile"
    RECONSTRUCT_DIRECTORY = "ReconstructDirectory"
    LOAD_GENERATION_SETTINGS = "LoadGenerationSettings"
    SAVE_GENERATION_SETTINGS = "SaveGenerationSettings"
    OPEN_RECONSTRUCTION = "OpenReconstruction"
    SAVE_RECONSTRUCTION = "SaveReconstruction"
    SAVE_RECONSTRUCTION_AS = "SaveReconstructionAs"
    CLOSE_RECONSTRUCTION = "CloseReconstruction"
    EXPORT_RECONSTRUCTION_WAV = "ExportReconstructionWav"
    EXPORT_RECONSTRUCTION_INSTRUMENTS = "ExportReconstructionInstruments"
    ADD_RECONSTRUCTION_TO_SEQUENCER = "AddReconstructionToSequencer"
    OPEN_RECONSTRUCTION_IN_EXPLORER = "OpenReconstructionInExplorer"
    LOCATE_ORIGINAL_AUDIO = "LocateOriginalAudio"
    PLAY = "Play"
    PLAY_FROM_START = "PlayFromStart"
    STOP = "Stop"
    TOGGLE_AUTOPLAY = "ToggleAutoplay"
    TOGGLE_FOLLOW_PLAYBACK = "ToggleFollowPlayback"
    TOGGLE_LOOP_SONG = "ToggleLoopSong"
    AUDIO_SETTINGS = "AudioSettings"
    TOGGLE_ADVANCED_SETTINGS = "ToggleAdvancedSettings"
    TOGGLE_FULLSCREEN = "ToggleFullscreen"
    ABOUT_DIALOG = "AboutDialog"
    NEXT_TAB = "NextTab"
    PREVIOUS_TAB = "PreviousTab"
