# automatically generated by the FlatBuffers compiler, do not modify

# namespace: configs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBConfig(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBConfig
    def General(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.configs.FBGeneralConfig import FBGeneralConfig

            obj = FBGeneralConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBConfig
    def Library(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.configs.FBLibraryConfig import FBLibraryConfig

            obj = FBLibraryConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBConfig
    def Generation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.configs.FBGenerationConfig import FBGenerationConfig

            obj = FBGenerationConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def FBConfigStart(builder):
    builder.StartObject(3)


def Start(builder):
    return FBConfigStart(builder)


def FBConfigAddGeneral(builder, general):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(general), 0)


def AddGeneral(builder, general):
    return FBConfigAddGeneral(builder, general)


def FBConfigAddLibrary(builder, library):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(library), 0)


def AddLibrary(builder, library):
    return FBConfigAddLibrary(builder, library)


def FBConfigAddGeneration(builder, generation):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(generation), 0)


def AddGeneration(builder, generation):
    return FBConfigAddGeneration(builder, generation)


def FBConfigEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBConfigEnd(builder)
