# automatically generated by the FlatBuffers compiler, do not modify

# namespace: configs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBGenerationConfig(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBGenerationConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBGenerationConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBGenerationConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBGenerationConfig
    def Mixer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FBGenerationConfig
    def ResetPhase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBGenerationConfig
    def Generators(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FBGenerationConfig
    def GeneratorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBGenerationConfig
    def GeneratorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FBGenerationConfig
    def Calculation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.configs.FBCalculationConfig import FBCalculationConfig

            obj = FBCalculationConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBGenerationConfig
    def Weights(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from schemas.configs.FBWeightsConfig import FBWeightsConfig

            obj = FBWeightsConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def FBGenerationConfigStart(builder):
    builder.StartObject(5)


def Start(builder):
    return FBGenerationConfigStart(builder)


def FBGenerationConfigAddMixer(builder, mixer):
    builder.PrependFloat32Slot(0, mixer, 0.0)


def AddMixer(builder, mixer):
    return FBGenerationConfigAddMixer(builder, mixer)


def FBGenerationConfigAddResetPhase(builder, resetPhase):
    builder.PrependBoolSlot(1, resetPhase, 0)


def AddResetPhase(builder, resetPhase):
    return FBGenerationConfigAddResetPhase(builder, resetPhase)


def FBGenerationConfigAddGenerators(builder, generators):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(generators), 0)


def AddGenerators(builder, generators):
    return FBGenerationConfigAddGenerators(builder, generators)


def FBGenerationConfigStartGeneratorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartGeneratorsVector(builder, numElems):
    return FBGenerationConfigStartGeneratorsVector(builder, numElems)


def FBGenerationConfigAddCalculation(builder, calculation):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(calculation), 0)


def AddCalculation(builder, calculation):
    return FBGenerationConfigAddCalculation(builder, calculation)


def FBGenerationConfigAddWeights(builder, weights):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(weights), 0)


def AddWeights(builder, weights):
    return FBGenerationConfigAddWeights(builder, weights)


def FBGenerationConfigEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBGenerationConfigEnd(builder)
