# automatically generated by the FlatBuffers compiler, do not modify

# namespace: configs

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBGeneralConfig(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBGeneralConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBGeneralConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBGeneralConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBGeneralConfig
    def MinPitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBGeneralConfig
    def MaxPitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBGeneralConfig
    def Normalize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBGeneralConfig
    def Quantize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # FBGeneralConfig
    def MaxWorkers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBGeneralConfig
    def LibraryDirectory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBGeneralConfig
    def OutputDirectory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def FBGeneralConfigStart(builder):
    builder.StartObject(7)


def Start(builder):
    return FBGeneralConfigStart(builder)


def FBGeneralConfigAddMinPitch(builder, minPitch):
    builder.PrependInt32Slot(0, minPitch, 0)


def AddMinPitch(builder, minPitch):
    return FBGeneralConfigAddMinPitch(builder, minPitch)


def FBGeneralConfigAddMaxPitch(builder, maxPitch):
    builder.PrependInt32Slot(1, maxPitch, 0)


def AddMaxPitch(builder, maxPitch):
    return FBGeneralConfigAddMaxPitch(builder, maxPitch)


def FBGeneralConfigAddNormalize(builder, normalize):
    builder.PrependBoolSlot(2, normalize, 0)


def AddNormalize(builder, normalize):
    return FBGeneralConfigAddNormalize(builder, normalize)


def FBGeneralConfigAddQuantize(builder, quantize):
    builder.PrependBoolSlot(3, quantize, 0)


def AddQuantize(builder, quantize):
    return FBGeneralConfigAddQuantize(builder, quantize)


def FBGeneralConfigAddMaxWorkers(builder, maxWorkers):
    builder.PrependInt32Slot(4, maxWorkers, 0)


def AddMaxWorkers(builder, maxWorkers):
    return FBGeneralConfigAddMaxWorkers(builder, maxWorkers)


def FBGeneralConfigAddLibraryDirectory(builder, libraryDirectory):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(libraryDirectory), 0)


def AddLibraryDirectory(builder, libraryDirectory):
    return FBGeneralConfigAddLibraryDirectory(builder, libraryDirectory)


def FBGeneralConfigAddOutputDirectory(builder, outputDirectory):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(outputDirectory), 0)


def AddOutputDirectory(builder, outputDirectory):
    return FBGeneralConfigAddOutputDirectory(builder, outputDirectory)


def FBGeneralConfigEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBGeneralConfigEnd(builder)
