# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fft

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBWindow(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBWindow()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBWindow(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBWindow
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBWindow
    def Config(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from sampletones_schemas.configs.FBInstructionsLibraryConfig import FBInstructionsLibraryConfig

            obj = FBInstructionsLibraryConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FBWindow
    def On(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # FBWindow
    def CustomSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0


def FBWindowStart(builder):
    builder.StartObject(3)


def Start(builder):
    return FBWindowStart(builder)


def FBWindowAddConfig(builder, config):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(config), 0)


def AddConfig(builder, config):
    return FBWindowAddConfig(builder, config)


def FBWindowAddOn(builder, on):
    builder.PrependBoolSlot(1, on, 1)


def AddOn(builder, on):
    return FBWindowAddOn(builder, on)


def FBWindowAddCustomSize(builder, customSize):
    builder.PrependInt32Slot(2, customSize, 0)


def AddCustomSize(builder, customSize):
    return FBWindowAddCustomSize(builder, customSize)


def FBWindowEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBWindowEnd(builder)
