# automatically generated by the FlatBuffers compiler, do not modify

# namespace: instructions


class FBInstruction(object):
    NONE = 0
    schemas_instructions_FBPulseInstruction = 1
    schemas_instructions_FBTriangleInstruction = 2
    schemas_instructions_FBNoiseInstruction = 3
