# automatically generated by the FlatBuffers compiler, do not modify

# namespace: instructions

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBInstructionData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBInstructionData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBInstructionData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBInstructionData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBInstructionData
    def InstructionClass(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBInstructionData
    def InstructionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FBInstructionData
    def Instruction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table

            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None


def FBInstructionDataStart(builder):
    builder.StartObject(3)


def Start(builder):
    return FBInstructionDataStart(builder)


def FBInstructionDataAddInstructionClass(builder, instructionClass):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(instructionClass), 0)


def AddInstructionClass(builder, instructionClass):
    return FBInstructionDataAddInstructionClass(builder, instructionClass)


def FBInstructionDataAddInstructionType(builder, instructionType):
    builder.PrependUint8Slot(1, instructionType, 0)


def AddInstructionType(builder, instructionType):
    return FBInstructionDataAddInstructionType(builder, instructionType)


def FBInstructionDataAddInstruction(builder, instruction):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(instruction), 0)


def AddInstruction(builder, instruction):
    return FBInstructionDataAddInstruction(builder, instruction)


def FBInstructionDataEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBInstructionDataEnd(builder)
