SAMPLETONES_NAME = "SampleToNES"
SAMPLETONES_VERSION = "0.2.0"
SAMPLETONES_NAME_VERSION = f"{SAMPLETONES_NAME} v{SAMPLETONES_VERSION}"

SAMPLETONES_AUTHOR = "Jakim"
SAMPLETONES_GROUP = "Stage Magician"
