from typing import Optional, Protocol


class BaseLogger(Protocol):
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def critical(self, message: str) -> None: ...
    def error_with_traceback(self, exception: BaseException, message: Optional[str] = None) -> None: ...
