# GUI Constants

# Window dimensions
DIM_WINDOW_WIDTH = 1280
DIM_WINDOW_HEIGHT = 800

# Layout dimensions
DIM_PANEL_WIDTH_MAIN_EXPLORER = 440
DIM_PANEL_HEIGHT_MAIN_EXPLORER = -1
DIM_PANEL_WIDTH_LEFT = 360
DIM_PANEL_HEIGHT_LEFT = -1
DIM_PANEL_WIDTH_RIGHT = 460
DIM_PANEL_HEIGHT_RIGHT = -1
DIM_PANEL_WIDTH_INSTRUCTIONS_DETAILS = 360
DIM_PANEL_WIDTH_RECONSTRUCTIONS_DETAILS = 420

# File dialog dimensions
DIM_DIALOG_HEIGHT_TRACEBACK = 400
DIM_DIALOG_WIDTH_TRACEBACK = 0
DIM_DIALOG_WIDTH_FILE = 720
DIM_DIALOG_HEIGHT_FILE = 400
DIM_DIALOG_WIDTH_DEFAULT = 350
DIM_DIALOG_HEIGHT_DEFAULT = 0
DIM_DIALOG_WIDTH_ERROR = 600
DIM_DIALOG_HEIGHT_ERROR = 120
DIM_DIALOG_WIDTH_ERROR_WRAP = DIM_DIALOG_WIDTH_ERROR - 10
DIM_PANEL_HEIGHT_MAIN_CONFIG = 258
DIM_PANEL_HEIGHT_MAIN_CONVERTER = 260
DIM_PANEL_HEIGHT_MAIN_ADVANCED = 162

# UI element dimensions
DIM_BUTTON_WIDTH_MAIN_CONVERTER = -1
DIM_BUTTON_HEIGHT_MAIN_CONVERTER = 45
DIM_INPUT_WIDTH_DEFAULT = -180

# Search UI dimensions
DIM_INPUT_WIDTH_SEARCH = -80
DIM_BUTTON_WIDTH_SEARCH = -1
DIM_BUTTON_WIDTH_COPY = 60

# Input validation ranges
VAL_RANGE_MAIN_ADVANCED_MAX_WORKERS = 1

# GUI Labels
TTL_WINDOW_MAIN = "SampleToNES"

# Menu labels
LBL_MENU_GROUP_FILE = "File"
LBL_MENU_ITEM_FILE_SAVE_CONFIG = "Save configuration"
LBL_MENU_ITEM_FILE_LOAD_CONFIG = "Load configuration"
LBL_MENU_ITEM_FILE_AUDIO_SETTINGS = "Audio settings"
LBL_MENU_ITEM_FILE_EXIT = "Exit"

LBL_MENU_GROUP_RECONSTRUCTION = "Reconstruction"
LBL_MENU_ITEM_RECONSTRUCTION_RECONSTRUCT_FILE = "Reconstruct file"
LBL_MENU_ITEM_RECONSTRUCTION_RECONSTRUCT_DIRECTORY = "Reconstruct directory"
LBL_MENU_ITEM_RECONSTRUCTION_CLOSE_RECONSTRUCTION = "Close reconstruction"
LBL_MENU_ITEM_RECONSTRUCTION_LOAD_RECONSTRUCTION = "Load reconstruction"
LBL_MENU_ITEM_RECONSTRUCTION_EXPORT_RECONSTRUCTION_WAV = "Export reconstruction as WAV"
LBL_MENU_ITEM_RECONSTRUCTION_EXPORT_RECONSTRUCTION_FTIS = "Export reconstruction as FTIs"

LBL_MENU_GROUP_PLAYBACK = "Playback"
LBL_MENU_ITEM_PLAYBACK_PLAY_FROM_START = "Play from start"
LBL_MENU_ITEM_PLAYBACK_PLAY = "Play"
LBL_MENU_ITEM_PLAYBACK_PAUSE = "Pause"
LBL_MENU_ITEM_PLAYBACK_STOP = "Stop"
LBL_MENU_ITEM_PLAYBACK_AUTOPLAY = "Autoplay"

LBL_MENU_GROUP_VIEW = "View"
LBL_MENU_ITEM_VIEW_FULLSCREEN = "Fullscreen"
LBL_MENU_ITEM_VIEW_SHOW_ADVANCED_SETTINGS = "Show advanced settings"

# Menu item tags
TAG_MENU_ITEM_RECONSTRUCTION_RECONSTRUCT_FILE = "menu_item_reconstruction_reconstruct_file"
TAG_MENU_ITEM_RECONSTRUCTION_RECONSTRUCT_DIRECTORY = "menu_item_reconstruction_reconstruct_directory"
TAG_MENU_ITEM_RECONSTRUCTION_CLOSE_RECONSTRUCTION = "menu_item_reconstruction_close_reconstruction"
TAG_MENU_ITEM_RECONSTRUCTION_LOAD_RECONSTRUCTION = "menu_item_reconstruction_load_reconstruction"
TAG_MENU_ITEM_RECONSTRUCTION_EXPORT_RECONSTRUCTION_WAV = "menu_item_reconstruction_export_reconstruction_wav"
TAG_MENU_ITEM_RECONSTRUCTION_EXPORT_RECONSTRUCTION_FTIS = "menu_item_reconstruction_export_reconstruction_ftis"
TAG_MENU_ITEM_VIEW_FULLSCREEN = "menu_item_view_fullscreen"
TAG_MENU_ITEM_VIEW_SHOW_ADVANCED_SETTINGS = "menu_item_view_show_advanced_settings"
TAG_MENU_ITEM_PLAYBACK_PLAY_FROM_START = "menu_item_playback_play_from_start"
TAG_MENU_ITEM_PLAYBACK_PLAY = "menu_item_playback_play"
TAG_MENU_ITEM_PLAYBACK_STOP = "menu_item_playback_stop"
TAG_MENU_ITEM_PLAYBACK_AUTOPLAY = "menu_item_playback_autoplay"

# Tab labels
LBL_TAB_MAIN = "Main"
LBL_TAB_INSTRUCTIONS = "Instructions"
LBL_TAB_RECONSTRUCTIONS = "Reconstructions"

# Section headers
LBL_SECTION_MAIN_CONFIG = "General settings"
LBL_SECTION_MAIN_ADVANCED = "Advanced settings"
LBL_SECTION_MAIN_CONFIG_LIBRARY_SETTINGS = "Instructions library settings"
LBL_SECTION_MAIN_RECONSTRUCTOR = "Generators"
LBL_SECTION_MAIN_CONVERTER = "Converter"

# Button labels
LBL_BUTTON_MAIN_EXPLORER_COLLAPSE_ALL = "Collapse all"
LBL_BUTTON_MAIN_ADVANCED_SELECT_OUTPUT_DIRECTORY = "Select output directory"
LBL_BUTTON_MAIN_ADVANCED_SELECT_LIBRARY_DIRECTORY = "Select instructions data directory"
LBL_BUTTON_INSTRUCTIONS_LIBRARY_GENERATE_LIBRARY = "Generate library"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_FILE = "Reconstruct file"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_DIRECTORY = "Reconstruct directory"
LBL_BUTTON_INSTRUCTIONS_LIBRARY_REGENERATE_LIBRARY = "Regenerate instructions"
LBL_BUTTON_INSTRUCTIONS_LIBRARY_REFRESH_LIBRARIES = "Refresh instructions data"
LBL_BUTTON_RECONSTRUCTIONS_BROWSER_REFRESH_LIST = "Refresh reconstructions"
LBL_BUTTON_TREE_CLEAR_SEARCH = "Clear"
LBL_BUTTON_MAIN_CONVERTER_CLOSE = "Close"
LBL_BUTTON_MAIN_CONVERTER_CANCEL = "Cancel"
LBL_BUTTON_MAIN_CONVERTER_LOAD = "Load"
LBL_BUTTON_MAIN_CONVERTER_CONVERT_SAMPLE = "Convert sample"
LBL_BUTTON_MAIN_CONVERTER_CONVERT_DIRECTORY = "Convert directory"

# Checkbox labels
LBL_CHECKBOX_MAIN_CONFIG_NORMALIZE_AUDIO = "Normalize audio"
LBL_CHECKBOX_MAIN_CONFIG_QUANTIZE_AUDIO = "Quantize audio"
LBL_CHECKBOX_TRIANGLE = "Triangle"
LBL_CHECKBOX_PULSE_1 = "Pulse 1"
LBL_CHECKBOX_PULSE_2 = "Pulse 2"
LBL_CHECKBOX_NOISE = "Noise"

# Input field labels
LBL_INPUT_MAIN_ADVANCED_MAX_WORKERS = "Workers"
LBL_INPUT_MAIN_CONFIG_SAMPLE_RATE = "Sample rate"
LBL_INPUT_MAIN_CONFIG_CHANGE_RATE = "NES frequency"

# Tree
LBL_TREE_ROOT = "Root"
LBL_TREE_SEARCH = "Search"
LBL_TREE_FILTER = "Filter"

# Buttons suffixes
SUF_BUTTON = "_button"
SUF_BUTTON_COPY = f"{SUF_BUTTON}_copy"
SUF_BUTTON_OK = f"{SUF_BUTTON}_ok"
SUF_BUTTON_RESET_X = f"{SUF_BUTTON}_reset_x"
SUF_BUTTON_RESET_Y = f"{SUF_BUTTON}_reset_y"
SUF_BUTTON_RESET_ALL = f"{SUF_BUTTON}_reset_all"
SUF_BUTTON_SEARCH = f"{SUF_BUTTON}_search"
SUF_BUTTON_SHOW_TRACEBACK = f"{SUF_BUTTON}_show_traceback"

# Tooltip labels
LBL_TOOLTIP_MAIN_CONFIG_NORMALIZE = "Normalize audio to ensure consistent volume levels."
LBL_TOOLTIP_MAIN_CONFIG_QUANTIZE = "Quantize audio samples to 5-bit resolution."
LBL_TOOLTIP_MAIN_ADVANCED_MAX_WORKERS = "Set the number parallel workers for audio processing tasks."
LBL_TOOLTIP_MAIN_CONFIG_SAMPLE_RATE = "Set the sample rate (in Hz) for audio processing."
LBL_TOOLTIP_MAIN_CONFIG_CHANGE_RATE = (
    "Set the NES refresh rate (in Hz) for audio processing. NTSC = 60 Hz, PAL = 50 Hz."
)
LBL_TOOLTIP_MAIN_TRANSFORMATION_GAMMA = (
    "Interpolate between linear spectral features (0) features and logarithmic ones (100)."
)
LBL_TOOLTIP_MAIN_RECONSTRUCTOR_MIXER = (
    "Amplify the NES generated audio. Lower values introduce compression, while higher values increase dynamics."
)

# Dialog titles
TTL_DIALOG_SAVE_CONFIG = "Save configuration"
TTL_DIALOG_LOAD_CONFIG = "Load configuration"
TTL_DIALOG_LOAD_RECONSTRUCTION = "Load reconstruction"
TTL_DIALOG_RECONSTRUCT_FILE = "Reconstruct file"
TTL_DIALOG_RECONSTRUCT_DIRECTORY = "Reconstruct directory"
TTL_DIALOG_SELECT_LIBRARY_DIRECTORY = "Select library directory"
TTL_DIALOG_SELECT_OUTPUT_DIRECTORY = "Select output directory"
TTL_DIALOG_EXPORT_WAV = "Export WAV"
TTL_DIALOG_EXPORT_FTI = "Export FTI"
TTL_DIALOG_ERROR = "Error"
TTL_DIALOG_CONFIG_STATUS = "Configuration status"
TTL_DIALOG_CONVERTER = "Reconstruction progress"
TTL_DIALOG_FILE_NOT_FOUND = "File not found"
TTL_DIALOG_LIBRARY_NOT_LOADED = "Library not loaded"
TTL_DIALOG_LIBRARY_GENERATION_STATUS = "Library generation status"

# Plot labels
LBL_GRAPH_WAVEFORM_ORIGINAL = "Original"
LBL_GRAPH_WAVEFORM_RECONSTRUCTION = "Reconstruction"

# Status messages
MSG_TREE_NO_RESULTS_FOUND = "No results found."
MSG_CONFIGURATION_SAVED_SUCCESSFULLY = "Configuration saved successfully."
MSG_CONFIGURATION_LOADED_SUCCESSFULLY = "Configuration loaded successfully."
MSG_CONFIGURATION_SAVE_ERROR = "Error saving configuration."
MSG_CONFIGURATION_LOAD_ERROR = "Error loading configuration."
MSG_CONFIGURATION_INVALID_ERROR = "Invalid configuration file."
MSG_LIBRARY_DISPLAY_ERROR = "Error while displaying data."
TPL_RECONSTRUCTION_COMPLETE = "Reconstruction complete. Total error: {:.4f}"
TPL_INSTRUCTIONS_LIBRARY_GENERATION_PROGRESS = "Generating: {}/{} "
MSG_INSTRUCTIONS_LIBRARY_GENERATING = "Generating library..."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_SAVING = "Saving generated library..."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_SUCCESS = "Library generated successfully."
MSG_INSTRUCTIONS_LIBRARY_NOT_LOADED = "Library is not loaded. Please load or generate a library."
MSG_INSTRUCTIONS_LIBRARY_LOADING = "Library is loading..."
LBL_INSTRUCTIONS_LIBRARY_LIBRARIES = "Instructions data"
LBL_RECONSTRUCTIONS_BROWSER_RECONSTRUCTIONS = "Reconstructions"
LBL_INSTRUCTIONS_LIBRARY_AVAILABLE_LIBRARIES = "Instructions data"
TPL_INSTRUCTIONS_LIBRARY_NOT_EXISTS = "Library {} doesn't exist."
MSG_INSTRUCTIONS_LIBRARY_WINDOW_NOT_AVAILABLE = "Window not available."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_CANCELLATION = "Library generation cancelled."
MSG_INSTRUCTIONS_LIBRARY_GENERATION_FAILED = "Error generating library."
MSG_INSTRUCTIONS_LIBRARY_FILE_NOT_FOUND = "The library file could not be found."
MSG_INSTRUCTIONS_LIBRARY_FILE_LOAD_ERROR = "Error while loading the library file."
MSG_INSTRUCTIONS_LIBRARY_LOAD_ERROR = "Error while loading library data."
MSG_INSTRUCTIONS_LIBRARY_INVALID_DATA_ERROR = "Invalid library data file."
MSG_INSTRUCTIONS_LIBRARY_INVALID_DATA_VALUES_ERROR = "Library data contains invalid values."
TPL_INSTRUCTIONS_LIBRARY_INCOMPATIBLE_VERSION_ERROR = "Incompatible library data version: {}, expected {}."
MSG_RECONSTRUCTIONS_BROWSER_RECONSTRUCTION_FILE_NOT_FOUND = "The reconstruction file could not be found."
MSG_RECONSTRUCTIONS_BROWSER_RECONSTRUCTION_AUDIO_FILE_NOT_FOUND = (
    "The audio file of this reconstruction could not be found."
)
MSG_GLOBAL_INVALID_METADATA_ERROR = "Invalid file metadata."

# Template strings
TPL_INSTRUCTIONS_LIBRARY_LIBRARY_EXISTS = "Library {} exists."
TPL_INSTRUCTIONS_LIBRARY_LIBRARY_LOADED = "Library {} loaded."

# GUI element tags
TAG_PANEL_MAIN = "main_panel"
TAG_PANEL_MAIN_ADVANCED = "advanced_panel"
TAG_PANEL_MAIN_SETTINGS = "main_panel_settings"
TAG_PANEL_MAIN_CONFIG_CELL = "main_panel_config_cell"
TAG_PANEL_MAIN_RECONSTRUCTOR_CELL = "main_panel_reconstructor_cell"
TAG_PANEL_INSTRUCTIONS_LIBRARY = "library_panel"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION = "instruction_panel"
TAG_TEXT_INSTRUCTIONS_LIBRARY_STATUS = "library_status"
TAG_GROUP_INSTRUCTIONS_LIBRARY_CONTROLS = "library_controls_group"
TAG_GROUP_RECONSTRUCTIONS_BROWSER_CONTROLS = "browser_controls_group"
TAG_BUTTON_INSTRUCTIONS_LIBRARY_GENERATE_LIBRARY = "library_generate_button"
TAG_BUTTON_INSTRUCTIONS_LIBRARY_REFRESH_LIBRARIES = "library_refresh_button"
TAG_PROGRESS_INSTRUCTIONS_LIBRARY = "library_progress"
TAG_PATH_MAIN_ADVANCED_LIBRARY_DIRECTORY_DISPLAY = "library_directory_display"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_REFRESH_RECONSTRUCTIONS = "browser_refresh_list_button"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_FILE = "browser_reconstruct_file_button"
TAG_BUTTON_RECONSTRUCTIONS_BROWSER_RECONSTRUCT_DIRECTORY = "browser_reconstruct_directory_button"
TAG_PATH_MAIN_ADVANCED_OUTPUT_DIRECTORY_DISPLAY = "output_directory_display"
TAG_DIALOG_GLOBAL_CONFIG_STATUS = "config_status_popup"
TAG_PANEL_MAIN_CONFIG = "config_panel"
TAG_CHECKBOX_MAIN_CONFIG_NORMALIZE = "normalize"
TAG_CHECKBOX_MAIN_CONFIG_QUANTIZE = "quantize"
TAG_INPUT_MAIN_ADVANCED_MAX_WORKERS = "max_workers"
TAG_GROUP_MAIN_ADVANCED_LIBRARY_DIRECTORY = "config_paths_instructions_group"
TAG_INPUT_MAIN_CONFIG_SAMPLE_RATE = "sample_rate"
TAG_INPUT_MAIN_CONFIG_CHANGE_RATE = "change_rate"
TAG_TREE_INSTRUCTIONS_LIBRARY = "libraries_tree"
TAG_GROUP_INSTRUCTIONS_LIBRARY_TREE = "libraries_tree_group"
TAG_WINDOW_INSTRUCTIONS_LIBRARY_TREE = "libraries_tree_window"
TAG_DIALOG_INSTRUCTIONS_LIBRARY_LIBRARY_NOT_LOADED = "library_not_loaded_dialog"
TAG_RECONSTRUCTION_NOT_LOADED_DIALOG = "reconstruction_not_loaded_dialog"
TAG_DIALOG_GLOBAL_PATH_MESSAGE = "path_message_dialog"
TAG_BUTTON_MAIN_ADVANCED_SELECT_LIBRARY_DIRECTORY = "config_library_directory"
TAG_BUTTON_MAIN_EXPLORER_COLLAPSE_ALL = "collapse_all"

# Indices and offsets
VAL_GLOBAL_DEFAULT_FLOAT = 0.0
VAL_GLOBAL_PROGRESS_START = 0.0
VAL_GLOBAL_PROGRESS_COMPLETE = 1.0

# Main GUI tags
TAG_WINDOW_MAIN = "main_window"
TAG_TABS = "tabs"
TAG_TAB_MAIN = "tab_main"
TAG_TAB_INSTRUCTIONS = "tab_instructions"
TAG_TAB_RECONSTRUCTIONS = "tab_reconstructions"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_PLAYER = "instruction_player_panel"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_WAVEFORM = "instruction_waveform_display"
TAG_PANEL_INSTRUCTIONS_INSTRUCTION_SPECTRUM = "instruction_spectrum_display"
TAG_TEXT_INSTRUCTIONS_DETAILS_INFO = "instruction_details_info"
TAG_PANEL_INSTRUCTIONS_DETAILS = "instruction_details"
TAG_PROGRESS_MAIN_CONVERTER = "converter_progress"
TAG_TEXT_MAIN_CONVERTER_STATUS = "converter_status"
TAG_PANEL_MAIN_CONVERTER = "converter_panel"
TAG_GROUP_MAIN_CONVERTER = "converter_subpanel"
TAG_PATH_MAIN_CONVERTER_INPUT_PATH = "converter_input_path_text"
TAG_TEXT_MAIN_CONVERTER_OUTPUT_PATH = "converter_output_path_text"
TAG_BUTTON_MAIN_CONVERTER_LOAD = "converter_load_button"
TAG_BUTTON_MAIN_CONVERTER_CANCEL = "converter_cancel_button"
TAG_DIALOG_MAIN_CONVERTER_SUCCESS = "converter_success_dialog"
TAG_BUTTON_MAIN_CONVERTER_CONVERT = "converter_convert_button"
TAG_DIALOG_GLOBAL_FILE_NOT_FOUND = "file_not_found_dialog"
TAG_DIALOG_GLOBAL_ERROR = "error_dialog"


# Messages
MSG_MAIN_CONVERTER_ERROR = "Reconstruction failed."
MSG_MAIN_CONVERTER_SUCCESS = "Reconstruction completed successfully!"
MSG_MAIN_CONVERTER_CONFIG_NOT_AVAILABLE = "Configuration not available"
MSG_MAIN_CONVERTER_RECONSTRUCTION_COMPLETED = "Reconstruction completed!"
MSG_MAIN_CONVERTER_NO_FILES_TO_PROCESS = "No WAV files found to process."
MSG_MAIN_CONVERTER_IDLE = "No tasks in progress."
MSG_MAIN_CONVERTER_WAITING = "Waiting to start..."
MSG_MAIN_CONVERTER_GENERATING_LIBRARY = "Generating instructions library..."
MSG_MAIN_CONVERTER_CANCELLING = "Aborting the conversion..."
MSG_MAIN_CONVERTER_CANCELLED = "Conversion cancelled."
TPL_MAIN_CONVERTER_PROGRESS = "Progress: {}/{} files"
TPL_GLOBAL_TIME_ESTIMATION = " (ETA: {eta_string})"
MSG_MAIN_CONVERTER_INPUT = "Input:"
MSG_MAIN_CONVERTER_OUTPUT = "Output:"

# Template strings
TPL_TAG_CHECKBOX_MAIN_RECONSTRUCTION_GENERATOR = "gen_{}"

# File dialog settings
VAL_DIALOG_GLOBAL_FILE_COUNT_SINGLE = 1
VAL_DIALOG_GLOBAL_DEFAULT_CONFIG_FILENAME = "config"

# Plot settings
VAL_PLOT_WIDTH_GLOBAL_FULL = -1
VAL_FONT_SCALE = 1
VAL_FONT_SIZE = 22
VAL_FONT_SIZE_SMALL = 19
VAL_FONT_SIZE_LARGE = 26

# Font tags
TAG_FONT_BOLD = "font_bold"
TAG_FONT_BOLD_SMALL = "font_bold_small"
TAG_FONT_BOLD_LARGE = "font_bold_large"
TAG_FONT_REGULAR = "font_regular"
TAG_FONT_REGULAR_SMALL = "font_regular_small"
TAG_FONT_REGULAR_LARGE = "font_regular_large"
TAG_FONT_ICON = "font_icon"

CHR_STAR = 0x2605  # Unicode star character

# Waveform display settings
DIM_WAVEFORM_HEIGHT = 300
COL_WAVEFORM_LAYER_SAMPLE = (100, 200, 255, 255)
COL_WAVEFORM_LAYER_RECONSTRUCTION = (255, 200, 100, 255)
COL_WAVEFORM_POSITION_INDICATOR = (255, 255, 255, 255)
VAL_WAVEFORM_SAMPLE_THICKNESS = 1.5
VAL_WAVEFORM_RECONSTRUCTION_THICKNESS = 1.2
VAL_WAVEFORM_POSITION_INDICATOR_THICKNESS = 2.0
VAL_WAVEFORM_ZOOM_FACTOR = 1.1
VAL_WAVEFORM_DEFAULT_Y_MIN = -1.0
VAL_WAVEFORM_DEFAULT_Y_MAX = 1.0
VAL_WAVEFORM_AXIS_SLOT = 1
SUF_WAVEFORM_POSITION_INDICATOR = "_position_indicator"

# Converter window settings
COL_PATH_TEXT = (100, 150, 255)
COL_PATH_TEXT_HOVER = (150, 200, 255)
SUF_PATH_HANDLER = "_handler"
SUF_INFO_DIALOG = "_info_dialog"

# Waveform labels and messages
LBL_PLOT_LABEL_WAVEFORM = "Waveform display"
LBL_PLOT_AXIS_WAVEFORM_TIME = "Time (samples)"
LBL_PLOT_AXIS_WAVEFORM_AMPLITUDE = "Amplitude"
LBL_PLOT_NAME_WAVEFORM_SAMPLE = "Sample"

# Button labels for waveform
LBL_BUTTON_WAVEFORM_RESET_X = "Reset X"
LBL_BUTTON_WAVEFORM_RESET_Y = "Reset Y"
LBL_BUTTON_WAVEFORM_RESET_ALL = "Reset all"

# Boolean values
VAL_CHECKBOX_MAIN_RECONSTRUCTOR_ENABLED = True
VAL_WINDOW_PRIMARY = True

# Audio player constants
DIM_PANEL_WIDTH_PLAYER = -1
DIM_PANEL_HEIGHT_PLAYER = 76
DIM_TABLE_HEIGHT_CONTROLS = 32
LBL_BUTTON_PLAYER_PLAY = "Play"
LBL_BUTTON_PLAYER_PAUSE = "Pause"
LBL_BUTTON_PLAYER_RESUME = "Resume"
LBL_BUTTON_PLAYER_STOP = "Stop"
MSG_PLAYER_NO_AUDIO_LOADED = "No audio loaded."
MSG_PLAYER_AUDIO_PLAYBACK_ERROR = "Audio playback error."
TTL_DIALOG_PLAYER_NO_AUDIO = "No Audio"

# Instruction panel constants
LBL_TEXT_INSTRUCTIONS_DETAILS_INSTRUCTION_DETAILS = "Instruction details"
MSG_INSTRUCTIONS_DETAILS_NO_SELECTION = "No instruction selected."
LBL_INSTRUCTIONS_INSTRUCTION_WAVEFORM = "Instruction waveform"
LBL_INSTRUCTIONS_INSTRUCTION_SPECTRUM = "Instruction spectrum"

# Reconstruction panel constants
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION = "reconstruction_panel"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION_PLAYER = "reconstruction_player_panel"
TAG_PANEL_RECONSTRUCTIONS_RECONSTRUCTION_WAVEFORM = "reconstruction_waveform_display"
TAG_PANEL_RECONSTRUCTIONS_DETAILS = "reconstruction_details_panel"
TAG_TAB_BAR_RECONSTRUCTIONS_DETAILS = "reconstruction_details_tab_bar"
TAG_TEXT_RECONSTRUCTIONS_DETAILS_GENERATORS = "reconstruction_details_generators"
TAG_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTI = "reconstruction_export_fti_button"
TAG_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTIS = "reconstruction_export_ftis_button"
TAG_GROUP_RECONSTRUCTIONS_RECONSTRUCTION_GENERATORS = "reconstruction_generators_group"
TAG_GROUP_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "reconstruction_audio_source_group"
TPL_TAG_CHECKBOX_RECONSTRUCTIONS_RECONSTRUCTION_GENERATOR = "reconstruction_generator_{}"
TPL_TAG_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "reconstruction_audio_source_{}"
TAG_BUTTON_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV = "reconstruction_export_wav_button"
LBL_PLOT_LABEL_RECONSTRUCTIONS_RECONSTRUCION_WAVEFORM = "Reconstruction waveform"
LBL_TEXT_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "Play audio source:"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_RECONSTRUCTION_DETAILS = "Reconstruction details"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTI = "Export instrument to FTI"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_EXPORT_FTIS = "Export reconstruction as FTIs"
LBL_BUTTON_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV = "Export reconstruction to WAV"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_PITCH = "Pitch"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_HI_PITCH = "Hi-pitch"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_VOLUME = "Volume"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_ARPEGGIO = "Arpeggio"
LBL_PLOT_LABEL_RECONSTRUCTIONS_DETAILS_DUTY_CYCLE = "Duty cycle"
TPL_TEXT_RECONSTRUCTIONS_DETAILS_INITIAL_PITCH = "Initial pitch: {} ({})"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO = "_audio"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_PLOT = "_plot"
SUF_TREE_SEARCH_INPUT = "_search_input"
SUF_GROUP = "_group"
SUF_LABEL = "_label"
SUF_TRACEBACK = "_traceback"
SUF_PATH_TEXT = "_path_text"
SUF_TEXT = "_text"
LBL_BUTTON_TRACEBACK_COPY = "Copy to clipboard"
LBL_BUTTON_RECONSTRUCTIONS_DETAILS_COPY = "Copy"
LBL_BUTTON_GLOBAL_COPIED = "Copied!"
LBL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_ORIGINAL_AUDIO = "Original audio"
LBL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO = "Reconstruction"
LBL_BUTTON_TRACEBACK_SHOW = "Show traceback"
LBL_BUTTON_TRACEBACK_HIDE = "Hide traceback"
MSG_GLOBAL_RECONSTRUCTION_NO_DATA = "No reconstruction loaded."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV_SUCCESS = "Reconstruction rendered successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTI_SUCCESS = "Instrument saved successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTIS_SUCCESS = "Reconstruction instruments saved successfully."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_WAV_FAILED = "Reconstruction failed to save."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTI_FAILED = "Failed to export instrument as FTI."
MSG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_FTIS_FAILED = "Failed to export reconstruction as FTIs."
MSG_RECONSTRUCTIONS_BROWSER_FILE_LOAD_ERROR = "Failed to load reconstruction."
MSG_RECONSTRUCTIONS_BROWSER_INVALID_RECONSTRUCTION_VALUES = "Reconstruction contains invalid values."
MSG_RECONSTRUCTIONS_BROWSER_INVALID_RECONSTRUCTION_FILE = "Invalid reconstruction file."
MSG_RECONSTRUCTIONS_BROWSER_INCOMPATIBLE_RECONSTRUCTION_FILE = "Incompatible reconstruction version: {}, expected {}."
MSG_GLOBAL_CONFIG_SAVE_FAILED = "Failed to save configuration."
TTL_DIALOG_RECONSTRUCTIONS_RECONSTRUCTION_EXPORT_STATUS = "Export status"
TTL_DIALOG_RECONSTRUCTIONS_RECONSTRUCTION_NOT_LOADED = "Reconstruction not loaded"
VAL_RADIO_RECONSTRUCTIONS_RECONSTRUCTION_AUDIO_SOURCE = "selector"
LBL_TEXT_RECONSTRUCTIONS_DETAILS_GENERATORS = "Generators"

# Waveform layer colors
COL_WAVEFORM_DEFAULT = (255, 255, 255, 255)

# Waveform component suffixes
SUF_GRAPH_PLOT = "_plot"
SUF_GRAPH_X_AXIS = "_x_axis"
SUF_GRAPH_Y_AXIS = "_y_axis"
SUF_GRAPH_LEGEND = "_legend"
SUF_GRAPH_CONTROLS = "_controls"
SUF_GRAPH_INFO = "_info"
SUF_GRAPH_RAW_DATA = "_raw_data"
SUF_GRAPH_RAW_DATA_GROUP = "_raw_data_group"
SUF_BAR_PLOT_ZERO_LINE = "_zero_line"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_SEPARATOR = "_separator"
SUF_RECONSTRUCTIONS_RECONSTRUCTION_NO_DATA_MESSAGE = "_no_data_message"
SUF_RECONSTRUCTIONS_DETAILS_WINDOW = "_window"

SUF_PANEL_LEFT = "_left_panel"
SUF_PANEL_CENTER = "_center_panel"
SUF_PANEL_RIGHT = "_right_panel"

# Spectrum display settings
LBL_PLOT_LABEL_SPECTRUM = "Spectrum display"
VAL_OFFSET_SPECTRUM_LOG = 1e-2
VAL_MAX_SPECTRUM_GRAYSCALE = 255
LBL_PLOT_AXIS_SPECTRUM_X = ""
LBL_PLOT_AXIS_SPECTRUM_FREQUENCY = "Frequency"
LBL_PLOT_NAME_SPECTRUM = "Spectrum"

DIM_GRAPH_WIDTH = -1
DIM_GRAPH_HEIGHT = 200

# Boolean text values
LBL_GLOBAL_YES = "Yes"
LBL_GLOBAL_NO = "No"

# Default axis range
VAL_MIN_GRAPH_DEFAULT_X = 0.0
VAL_MAX_GRAPH_DEFAULT_X = 1.0

# Audio player component suffixes
SUF_PLAYER_PLAY = "_play"
SUF_PLAYER_PAUSE = "_pause"
SUF_PLAYER_STOP = "_stop"
SUF_PLAYER_POSITION = "_position"
SUF_PLAYER_CONTROLS_GROUP = "_controls_group"
SUF_PLAYER_NO_AUDIO_POPUP = "_no_audio_popup"
SUF_PLAYER_ERROR_POPUP = "_error_popup"

# Audio player text constants
LBL_TEXT_PLAYER_POSITION = "Position: "
LBL_TEXT_PLAYER_SAMPLES = " samples"
LBL_BUTTON_GLOBAL_OK = "OK"
TAG_BUTTON_GLOBAL_OK = "button_ok"

# Instruction display text constants
LBL_CELL_INSTRUCTIONS_DETAILS_GENERATOR = "Generator"
LBL_CELL_INSTRUCTIONS_DETAILS_NAME = "Instruction"
LBL_CELL_INSTRUCTIONS_DETAILS_FREQUENCY = "Frequency"
TPL_CELL_INSTRUCTIONS_DETAILS_FREQUENCY = "{:.2f} Hz"
TPL_CELL_INSTRUCTIONS_DETAILS_PITCH = "{} ({})"
LBL_CELL_INSTRUCTIONS_DETAILS_DUTY_CYCLE = "{:.1f}% ({})"
TPL_CELL_INSTRUCTIONS_DETAILS_PERIOD = "p{} ({})"
LBL_CELL_INSTRUCTIONS_DETAILS_NO_FREQUENCY = "N/A"
LBL_CELL_INSTRUCTIONS_DETAILS_SAMPLE_LENGTH = "Sample length"
LBL_CELL_INSTRUCTIONS_DETAILS_SAMPLES = " samples"
LBL_TEXT_INSTRUCTIONS_DETAILS_PARAMETERS = "Parameters"
LBL_TEXT_INSTRUCTIONS_DETAILS_GENERAL = "General"
VAL_PRECISION_INSTRUCTIONS_DETAILS_FLOAT = 4
SUF_GRAPH_INSTRUCTIONS_INSTRUCTION_WAVEFORM = "_waveform"
SUF_GRAPH_INSTRUCTIONS_INSTRUCTIONS_SPECTRUM = "_spectrum"

# Instruction details table tags
TAG_INSTRUCTION_DETAILS_GENERAL_TABLE = "instruction_details_general_table"
TAG_INSTRUCTION_DETAILS_PARAMETERS_TABLE = "instruction_details_parameters_table"
TAG_INSTRUCTION_DETAILS_GENERAL_HEADER = "instruction_details_general_header"
TAG_INSTRUCTION_DETAILS_PARAMETERS_HEADER = "instruction_details_parameters_header"
SUF_INSTRUCTION_DETAILS_TABLE = "_table"

# Instruction details table colors (dark gray with blue/purple tones)
COL_TABLE_BACKGROUND_HEADER = (45, 50, 65, 255)
COL_TABLE_BACKGROUND_ROW = (30, 32, 40, 255)
COL_TABLE_BACKGROUND_ROW_ALTERNATIVE = (38, 40, 52, 255)
COL_TABLE_BORDER = (60, 65, 85, 255)
COL_TABLE_LABEL = (140, 160, 200, 255)
COL_TABLE_VALUE = (200, 205, 220, 255)

# Instruction details table dimensions
DIM_TABLE_WIDHT_LABEL = 130
VAL_TABLE_CELL_PADDING = 8, 4
VAL_TABLE_FRAME_ROUNDING = 4

# Reconstructor panel constants
TAG_RECONSTRUCTOR_PANEL = "reconstructor_panel"
TAG_GROUP_MAIN_ADVANCED_OUTPUT_DIRECTORY = "reconstructor_output_directory_group"
TAG_BUTTON_MAIN_ADVANCED_SELECT_OUTPUT_DIRECTORY = "reconstructor_select_output_directory_button"
LBL_SECTION_RECONSTRUCTOR_SETTINGS = "Reconstructor settings"
LBL_SLIDER_RECONSTRUCTOR_MIXER = "Mixer volume"
LBL_SLIDER_CONFIG_TRANSFORMATION_GAMMA = "FFT transformation"
TAG_CONFIG_TRANSFORMATION_GAMMA = "transformation_gamma"
TAG_RECONSTRUCTOR_MIXER = "mixer"

# Explorer panel constants
TAG_EXPLORER_TREE = "explorer_tree"
TAG_EXPLORER_PANEL = "explorer_panel"
TAG_EXPLORER_TREE_WINDOW = "explorer_tree_window"
TAG_EXPLORER_TREE_GROUP = "explorer_tree_group"
TAG_EXPLORER_CONVERTER_RUNNING = "explorer_converter_running_info_dialog"
LBL_EXPLORER_FILESYSTEM = "Filesystem"
LBL_EXPLORER_CONTEXT_ITEM_LOAD_RECONSTRUCTION = "Load reconstruction"
LBL_EXPLORER_CONTEXT_ITEM_LOAD_LIBRARY = "Load instructions library"
LBL_EXPLORER_CONTEXT_ITEM_RECONSTRUCT_FILE = "Reconstruct file"
LBL_EXPLORER_CONTEXT_ITEM_RECONSTRUCT_DIRECTORY = "Reconstruct directory"
LBL_EXPLORER_CONTEXT_ITEM_MARK_AS_FAVORITE = "Mark as favorite"
LBL_EXPLORER_CONTEXT_ITEM_UNMARK_AS_FAVORITE = "Unmark as favorite"
LBL_EXPLORER_CONTEXT_ITEM_SET_AS_LIBRARY_DIRECTORY = "Set as instructions library directory"
LBL_EXPLORER_CONTEXT_ITEM_SET_AS_OUTPUT_DIRECTORY = "Set as output directory"
MSG_EXPLORER_CONVERTER_RUNNING = (
    "A conversion is already running. Please wait for it to complete or cancel the current operation "
    "before starting a new one."
)
TTL_EXPLORER_CONVERTER_RUNNING = "Conversion in progress"

# Browser panel constants
LBL_OUTPUT_AVAILABLE_RECONSTRUCTIONS = "Reconstructions"
TAG_BROWSER_PANEL = "browser_panel"
TAG_BROWSER_TREE = "browser_tree"
TAG_BROWSER_TREE_GROUP = "browser_tree_group"
TAG_BROWSER_TREE_WINDOW = "browser_tree_window"

# Node type constants
NOD_TYPE_ROOT = "root"
NOD_TYPE_LIBRARY = "library"
NOD_TYPE_LIBRARY_PLACEHOLDER = "library_placeholder"
NOD_TYPE_GENERATOR = "generator"
NOD_TYPE_GROUP = "group"
NOD_TYPE_INSTRUCTION = "instruction"
NOD_TYPE_DIRECTORY = "directory"
NOD_TYPE_FILE = "file"

# Node labels
NOD_LABEL_NOT_LOADED = "Click to load the library"
NOD_LABEL_LIBRARIES = "Libraries"

# Bar plot display settings
LBL_BAR_PLOT_DISPLAY = "Bar plot display"
MSG_BAR_PLOT_NO_DATA = "No data loaded."
COL_BAR_PLOT_DEFAULT = (100, 200, 255, 255)
COL_BAR_PLOT_PITCH = (100, 200, 255, 255)
COL_BAR_PLOT_VOLUME = (100, 255, 100, 255)
COL_BAR_PLOT_ARPEGGIO = (255, 150, 100, 255)
COL_BAR_PLOT_DUTY_CYCLE = (255, 200, 100, 255)
COL_BAR_PLOT_ZERO_LINE = (200, 200, 200, 255)
VAL_BAR_PLOT_DEFAULT_X_MIN = 0.0
VAL_BAR_PLOT_DEFAULT_Y_MIN = 0.0
VAL_BAR_PLOT_DEFAULT_Y_MAX = 100.0
VAL_BAR_PLOT_PITCH_Y_MIN = -128.0
VAL_BAR_PLOT_PITCH_Y_MAX = 127.0
VAL_BAR_PLOT_VOLUME_Y_MIN = 0.0
VAL_BAR_PLOT_VOLUME_Y_MAX = 15.0
VAL_BAR_PLOT_DUTY_CYCLE_Y_MIN = 0.0
VAL_BAR_PLOT_DUTY_CYCLE_Y_MAX = 3.0
VAL_BAR_PLOT_AXIS_SLOT = 1
VAL_BAR_PLOT_BAR_WEIGHT = 0.8
VAL_BAR_PLOT_ZERO_LINE_THICKNESS = 1.0
DIM_BAR_PLOT_DEFAULT_HEIGHT = 200

COL_TEXT_WHITE = (255, 255, 255, 255)
COL_TEXT_DEFAULT = (220, 220, 220, 255)
COL_TEXT_DISABLED_DEFAULT = (130, 130, 130, 255)

COL_TEXT_WAVE = (100, 200, 255, 255)
COL_TEXT_LIBRARY = (150, 255, 150, 255)
COL_TEXT_RECONSTRUCTION = (255, 200, 100, 255)
COL_TEXT_FAVORITE = (255, 215, 0, 255)

COL_BUTTON = (54, 54, 72, 255)
COL_BUTTON_ACTIVE = (90, 90, 120, 255)
COL_BUTTON_HOVERED = (72, 72, 108, 255)
COL_BUTTON_LIGHT = (64, 64, 96, 255)
VAL_BUTTON_FRAME_ROUNDING = 6
VAL_BUTTON_FRAME_PADDING = 10, 4

COL_ERROR_TEXT = (255, 100, 100, 255)
COL_TRACEBACK_TEXT = (192, 192, 192, 255)
COL_BACKGROUND = (36, 36, 36, 255)
COL_BACKGROUND_DARK = (28, 28, 28, 255)
COL_BACKGROUND_LIGHT = (44, 44, 44, 255)

VAL_WINDOW_POSITION_X = 200
VAL_WINDOW_POSITION_Y = 200
VAL_WINDOW_FULLSCREEN = False

TAG_THEME_DEFAULT = "theme_default"
TAG_THEME_CONVERTER = "theme_converter"
TAG_THEME_TABLE = "theme_table"

# Audio settings panel constants
TAG_AUDIO_SETTINGS_PANEL = "audio_settings_panel"
TAG_AUDIO_SETTINGS_WINDOW = "audio_settings_window"
TAG_AUDIO_SETTINGS_DEVICE_COMBO = "audio_settings_device_combo"
TAG_AUDIO_SETTINGS_SAMPLE_RATE_COMBO = "audio_settings_sample_rate_combo"
TAG_AUDIO_SETTINGS_DEVICE_GROUP = "audio_settings_device_group"
TAG_AUDIO_SETTINGS_SAMPLE_RATE_GROUP = "audio_settings_sample_rate_group"
TAG_AUDIO_SETTINGS_APPLY_BUTTON = "audio_settings_apply_button"
TAG_AUDIO_SETTINGS_REFRESH_BUTTON = "audio_settings_refresh_button"

LBL_AUDIO_SETTINGS_TITLE = "Audio settings"
LBL_AUDIO_SETTINGS_OUTPUT_DEVICE = "Output device"
LBL_AUDIO_SETTINGS_SAMPLE_RATE = "Sample rate"
LBL_AUDIO_SETTINGS_APPLY = "Apply"
LBL_AUDIO_SETTINGS_REFRESH_DEVICES = "Refresh devices"

DIM_AUDIO_SETTINGS_WINDOW_WIDTH = 600
DIM_AUDIO_SETTINGS_WINDOW_HEIGHT = 0
DIM_AUDIO_SETTINGS_COMBO_WIDTH = -1
DIM_AUDIO_SETTINGS_LABEL_WIDTH = 150

SUF_AUDIO_SETTINGS_HZ = " Hz"
SUF_AUDIO_SETTINGS_BIT = "-bit"

SUF_NODE_HANDLER = "_node_handler"
SUF_NODE_DUMMY = "_node_dummy"
