from pathlib import Path
from typing import Final

import pytest

from sampletones_core.compatibility.kind import ObjectKind
from sampletones_core.compatibility.upgrade import CURRENT_VERSIONS, UPDATES
from sampletones_shared.deployment.version import compare_versions
from tests.suite.compatibility import (
    ARCHIVED_VERSIONS,
    WRITING_RELEASE,
    archived,
    stored_version,
    writing_release,
)

KINDS: Final[tuple[ObjectKind, ...]] = tuple(ARCHIVED_VERSIONS)


class TestWhatTheCorpusHolds:
    """Each archived file is what its name says, written before the version this build reads."""

    @pytest.mark.parametrize("kind", KINDS, ids=lambda kind: kind.value)
    def test_every_format_keeps_an_archived_file(self, kind: ObjectKind) -> None:
        assert archived(kind, ARCHIVED_VERSIONS[kind]).is_file()

    @pytest.mark.parametrize("kind", KINDS, ids=lambda kind: kind.value)
    def test_a_file_states_the_version_it_is_named_after(self, kind: ObjectKind) -> None:
        """A file regenerated by a newer build would leave the chain idle while the tests stayed green."""
        version = ARCHIVED_VERSIONS[kind]

        assert stored_version(kind, archived(kind, version)) == version

    @pytest.mark.parametrize("kind", KINDS, ids=lambda kind: kind.value)
    def test_a_file_stands_before_the_version_this_build_writes(self, kind: ObjectKind) -> None:
        assert compare_versions(ARCHIVED_VERSIONS[kind], CURRENT_VERSIONS[kind]) < 0

    @pytest.mark.parametrize("kind", KINDS, ids=lambda kind: kind.value)
    def test_a_file_names_the_release_that_wrote_it(self, kind: ObjectKind) -> None:
        assert writing_release(archived(kind, ARCHIVED_VERSIONS[kind])) == WRITING_RELEASE


class TestWhatEveryStepIsHeldTo:
    """A registered step reads a version a release shipped, so the corpus holds a file at it."""

    @pytest.mark.parametrize("kind", KINDS, ids=lambda kind: kind.value)
    def test_every_step_reads_a_version_the_corpus_keeps(self, kind: ObjectKind) -> None:
        """Opening a step without archiving the file it reads leaves the step held to nothing.

        A version reads as three components where a step states it and as two where a release
        names it, so the two are compared as versions rather than as the strings they spell.
        """
        kept = [version for version in ARCHIVED_VERSIONS.values() if archived(kind, version).is_file()]
        for update in UPDATES.get(kind, ()):
            assert any(compare_versions(str(update.base), version) == 0 for version in kept)

    @pytest.mark.parametrize("kind", KINDS, ids=lambda kind: kind.value)
    def test_the_corpus_keeps_no_file_outside_its_format(self, kind: ObjectKind) -> None:
        directory = archived(kind, ARCHIVED_VERSIONS[kind]).parent
        extension = archived(kind, ARCHIVED_VERSIONS[kind]).suffix

        assert all(path.suffix == extension for path in directory.iterdir() if path.is_file())
