from typing import Final

INSTRUMENT_POINTER_BYTES: Final[int] = 2
SEQUENCE_ENABLE_MASK_BYTES: Final[int] = 1
SEQUENCE_POINTER_BYTES: Final[int] = 2
INSTRUMENT_DEFINITION_BYTES: Final[int] = INSTRUMENT_POINTER_BYTES + SEQUENCE_ENABLE_MASK_BYTES

SEQUENCE_LENGTH_BYTES: Final[int] = 1
SEQUENCE_LOOP_POINT_BYTES: Final[int] = 1
SEQUENCE_RELEASE_POINT_BYTES: Final[int] = 1
SEQUENCE_SETTING_BYTES: Final[int] = 1
SEQUENCE_ITEM_BYTES: Final[int] = 1
SEQUENCE_HEADER_BYTES: Final[int] = (
    SEQUENCE_LENGTH_BYTES + SEQUENCE_LOOP_POINT_BYTES + SEQUENCE_RELEASE_POINT_BYTES + SEQUENCE_SETTING_BYTES
)
