# automatically generated by the FlatBuffers compiler, do not modify

# namespace: arrays

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class FBCyclicArray(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBCyclicArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFBCyclicArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # FBCyclicArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBCyclicArray
    def Array(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return 0

    # FBCyclicArray
    def ArrayAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # FBCyclicArray
    def ArrayLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FBCyclicArray
    def ArrayIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FBCyclicArray
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBCyclicArray
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0


def FBCyclicArrayStart(builder):
    builder.StartObject(3)


def Start(builder):
    return FBCyclicArrayStart(builder)


def FBCyclicArrayAddArray(builder, array):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(array), 0)


def AddArray(builder, array):
    return FBCyclicArrayAddArray(builder, array)


def FBCyclicArrayStartArrayVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartArrayVector(builder, numElems):
    return FBCyclicArrayStartArrayVector(builder, numElems)


def FBCyclicArrayAddSampleRate(builder, sampleRate):
    builder.PrependInt32Slot(1, sampleRate, 0)


def AddSampleRate(builder, sampleRate):
    return FBCyclicArrayAddSampleRate(builder, sampleRate)


def FBCyclicArrayAddFrequency(builder, frequency):
    builder.PrependFloat32Slot(2, frequency, 0.0)


def AddFrequency(builder, frequency):
    return FBCyclicArrayAddFrequency(builder, frequency)


def FBCyclicArrayEnd(builder):
    return builder.EndObject()


def End(builder):
    return FBCyclicArrayEnd(builder)
